force-app/main/default/objects/City_Guide__c/City_Guide__c.object-meta.xml
<CustomObject>
    <label>City Guide</label>
    <nameField>
        <label>City Guide Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>City Guides</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_City_Guide__c/Contact_City_Guide__c.object-meta.xml
<CustomObject>
    <label>Contact City Guide</label>
    <nameField>
        <displayFormat>City Guide -{000}</displayFormat>
        <label>Contact City Guide Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact City Guide</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_City_Guide__c/fields/City_Guide__c.field-meta.xml
<CustomField>
    <fullName>City_Guide__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>City Guide</label>
    <referenceTo>City_Guide__c</referenceTo>
    <relationshipLabel>Contact City Guide</relationshipLabel>
    <relationshipName>Contact_City_Guide</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact_City_Guide__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>City Guide</relationshipLabel>
    <relationshipName>Contact_City_Guide</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Repository/ContactCityGuideRepository.cls
/**
 * @description       : 
 * @author            : Mohamed Tarek
 * @group             : 
 * @last modified on  : 02-12-2023
 * @last modified by  : Mohamed Tarek
**/
public  class ContactCityGuideRepository {
    private static ContactCityGuideRepository instance = null;
    private ContactCityGuideRepository() {}

    public static ContactCityGuideRepository getInstance() {
        if (instance == null) {
          instance = new ContactCityGuideRepository();
        }
        return instance;
      }
      public List<Contact_City_Guide__c> FindAllCityGuidesbyContactAndActive(String contactId){
        return [
            SELECT
            Name,
            City_Guide__c,
            End_Date__c
            FROM Contact_City_Guide__c
            WHERE Contact__c =: contactId
            AND Active__c =: true
          ];

      }

}