force-app/main/default/objects/City_Guide__c/City_Guide__c.object-meta.xml
<CustomObject>
    <label>City Guide</label>
    <nameField>
        <label>City Guide Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>City Guides</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/City_Guide__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/City_Guide__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <label>Duration (Days)</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Mapper/CityGuideMapper.cls
global class CityGuideMapper {
    String name;
    List<String> image;
    String city;
    Decimal price;
    Decimal duration;
    String Id;
   //List<CatalogueMapper> catalogs;
    public CityGuideMapper() {

    }

    public CityGuideMapper CityGuideobjectToMapper( City_Guide__c cityGuidesObject){
        
        CityGuideMapper cityGuideMapper = new CityGuideMapper();
        ImageListMapper ImageListMapperInstance = ImageListMapper.getInstance();
        cityGuideMapper.name = cityGuidesObject.Name;
        cityGuideMapper.image = ImageListMapperInstance.ConvertToImageList(cityGuidesObject.Image__c);
        cityGuideMapper.city = cityGuidesObject.City__c;
        cityGuideMapper.price = cityGuidesObject.Price__c;
        cityGuideMapper.duration = cityGuidesObject.Duration__c;
        cityGuideMapper.Id = cityGuidesObject.Id;

      return cityGuideMapper;
    }

    public  List<CityGuideMapper> CityGuideobjectListToMapperList(List<City_Guide__c> cityGuideObjectList){

        List<CityGuideMapper> mapperList = new List<CityGuideMapper>();

        for( City_Guide__c c : cityGuideObjectList ){

            mapperList.add(CityGuideobjectToMapper(c));
        }

        return mapperList;
      }

}