force-app/main/default/objects/City_Guide__c/City_Guide__c.object-meta.xml
<CustomObject>
    <label>City Guide</label>
    <nameField>
        <label>City Guide Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>City Guides</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/City_Guide__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <label>Duration (Days)</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact_City_Guide__c/Contact_City_Guide__c.object-meta.xml
<CustomObject>
    <label>Contact City Guide</label>
    <nameField>
        <displayFormat>City Guide -{000}</displayFormat>
        <label>Contact City Guide Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact City Guide</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_City_Guide__c/fields/City_Guide__c.field-meta.xml
<CustomField>
    <fullName>City_Guide__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>City Guide</label>
    <referenceTo>City_Guide__c</referenceTo>
    <relationshipLabel>Contact City Guide</relationshipLabel>
    <relationshipName>Contact_City_Guide</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact_City_Guide__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>City Guide</relationshipLabel>
    <relationshipName>Contact_City_Guide</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Service/CityGuideService.cls
public class CityGuideService {
    private static CityGuideService instance = null;
    CityGuideRepository cityGuideRepositoryInstance;
    public  ContactRepository contactRepositoryInstance;
    public CityGuideMapper cityGuideMapper = new CityGuideMapper();


    public CityGuideService() {
        cityGuideRepositoryInstance = CityGuideRepository.getInstance();
        contactRepositoryInstance = ContactRepository.getInstance();
    }

    public static CityGuideService getInstance() {
        if (instance == null) {
          instance = new CityGuideService();
        }
        return instance;
      }
    
      public List<CityGuideMapper> GetCityGuideList() {
        List<City_Guide__c> cityGuideObjectList = cityGuideRepositoryInstance.FindAllCityGuides();
        return CityGuideMapper.CityGuideobjectListToMapperList(cityGuideObjectList);
 
       }

       public void SetContactCityGuideList(String contactId, String cityGuideId) {
        City_Guide__c cityGuide =cityGuideRepositoryInstance.FindAllCityGuideById(cityGuideId);
        Contact contact = contactRepositoryInstance.findByRecordId(contactId);
        Contact_City_Guide__c contactCityGuideObjectList = new Contact_City_Guide__c();
        contactCityGuideObjectList.Contact__c = contact.Id;
        contactCityGuideObjectList.City_Guide__c = cityGuideId;
        contactCityGuideObjectList.Start_Date__c = date.today();
        if(!(cityGuide.Duration__c== null)){
        contactCityGuideObjectList.End_Date__c = date.today().addDays((Integer)cityGuide.Duration__c);}
        contactCityGuideObjectList.Active__c = true;
         
        insert contactCityGuideObjectList;
 
       }

}