force-app/main/default/objects/City_Guide__c/City_Guide__c.object-meta.xml
<CustomObject>
    <label>City Guide</label>
    <nameField>
        <label>City Guide Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>City Guides</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/City_Guide__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/City_Guide__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <label>Duration (Days)</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Repository/CityGuideRepository.cls
public class CityGuideRepository {
    private static CityGuideRepository instance = null;
    private CityGuideRepository() {}

    public static CityGuideRepository getInstance() {
        if (instance == null) {
          instance = new CityGuideRepository();
        }
        return instance;
      }

      public List<City_Guide__c> FindAllCityGuides(){
        return [
          SELECT
          Name,
          Id,
          Image__c,
          City__c,
          Price__c,
          Duration__c	
          FROM City_Guide__c
        ];
      }
      public City_Guide__c FindAllCityGuideById(String id){
        return [
          SELECT
          Name,
          Id,
          Image__c,
          City__c,
          Price__c,
          Duration__c	
          FROM City_Guide__c
          WHERE Id =:id
        ];
      }
}