force-app/main/default/objects/OpportunityLineItem/fields/Opportunity_Line_Item_Details__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Line_Item_Details__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Line Item Details</label>
    <referenceTo>Opprtunity_Line_Item_Details__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opprtunity_Line_Item_Details__c/Opprtunity_Line_Item_Details__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <label>Opprtunity Line Item Details Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opprtunity_Line_Item_Details__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Number of Bookings</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/AssignById.cls
global class AssignById {

    public AssignById(){}
    
    @InvocableMethod
    public static void assignById(List<Request> R1) {
        Request input = R1.get(0);
        List<Opprtunity_Line_Item_Details__c> oppItem = input.opportunityItemDetails;
        List<OpportunityLineItem> oppProduct= input.opportunityProduct;
        
        for(Integer i = 0; i < oppItem.size(); i++){
            oppProduct.get(i).Opportunity_Line_Item_Details__c = oppItem.get(i).Id;
            oppProduct.get(i).Quantity=oppItem.get(i).Booking__c;
       }
       update oppItem;
       update oppProduct;
    }

     global class  Request {

        @InvocableVariable
        global List<Opprtunity_Line_Item_Details__c> opportunityItemDetails;
    
        @InvocableVariable
        global List<OpportunityLineItem> opportunityProduct;

        public Request() {
    
        }
    }
}