force-app/main/default/objects/OpportunityLineItem/fields/Opportunity_Line_Item_Details__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Line_Item_Details__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Line Item Details</label>
    <referenceTo>Opprtunity_Line_Item_Details__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item_Detail__c/Quote_Line_Item_Detail__c.object-meta.xml
<CustomObject>
    <label>Quote Line Item Detail</label>
    <nameField>
        <label>Quote Line Item Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Line Items Detail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote_Line_Item_Detail__c/fields/Opportunity_Line_Item_Details__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Line_Item_Details__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Line Item Details</label>
    <referenceTo>Opprtunity_Line_Item_Details__c</referenceTo>
    <relationshipLabel>Quote Line Items Detail</relationshipLabel>
    <relationshipName>Quote_Line_Items_Detail</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Line_Item_Detail__c.field-meta.xml
<CustomField>
    <fullName>Line_Item_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Line Item Detail</label>
    <referenceTo>Quote_Line_Item_Detail__c</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>Quote_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Service/QuoteService.cls
public  class QuoteService {
    private static QuoteService instance = null;
    public  QuoteRepository quoteRepositoryInstance;
    public  QuoteLineItemRepository quoteLineItemRepositoryInstance;
    public  QuoteLineItemDetailRepository quoteLineItemDetailRepositoryInstance;
    public PackageServiceRepository packageServiceRepositoryInstance;
    public QuoteMapper quoteMapper = new QuoteMapper();


    private QuoteService() {
        quoteRepositoryInstance = QuoteRepository.getInstance();
        quoteLineItemRepositoryInstance = QuoteLineItemRepository.getInstance();
        quoteLineItemDetailRepositoryInstance = QuoteLineItemDetailRepository.getInstance();
        packageServiceRepositoryInstance = PackageServiceRepository.getInstance();

    }

    public static QuoteService getInstance() {
        if (instance == null) {
          instance = new QuoteService();
        }
        return instance;
      }

      public List<QuoteMapper> GetQuoteDetails(String packageServiceId){

        OpportunityLineItem packageService = packageServiceRepositoryInstance.findPackageServiceById(packageServiceId);
        List<Quote_Line_Item_Detail__c> quoteLineItemDetails = quoteLineItemDetailRepositoryInstance.findQuoteLineItemDetailBy(packageService.Opportunity_Line_Item_Details__c);
        List<Id> quoteLineItemDetailsidList = new List<Id>();
        for(Quote_Line_Item_Detail__c qD : quoteLineItemDetails){
            quoteLineItemDetailsidList.add(qD.Id);
        }
        List<QuoteLineItem> quoteLineItems = quoteLineItemRepositoryInstance.findQuoteLineItemByQuoteLineItemDetailsId(quoteLineItemDetailsidList);
        Map<Id,QuoteLineItem> quoteLineItemDetailsIdQuoteLineItem = new Map<Id,QuoteLineItem>();
        for(QuoteLineItem q : quoteLineItems){
            quoteLineItemDetailsIdQuoteLineItem.put(q.Line_Item_Detail__c,q);
        }
        quoteMapper.quoteObjectListToMapperList(quoteLineItemDetails, quoteLineItemDetailsIdQuoteLineItem);
        return null;

      }
}