force-app/main/default/objects/Opprtunity_Line_Item_Details__c/Opprtunity_Line_Item_Details__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <label>Opprtunity Line Item Details Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opprtunity_Line_Item_Details__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sub_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>vaccine</fullName>
            </value>
            <value>
                <fullName>PCR</fullName>
            </value>
            <value>
                <fullName>Honeymoon</fullName>
            </value>
            <value>
                <fullName>Group Travel</fullName>
            </value>
            <value>
                <fullName>Wellness</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Cultural and historical</fullName>
            </value>
            <value>
                <fullName>Water sports</fullName>
            </value>
            <value>
                <fullName>Adventure tours</fullName>
            </value>
            <value>
                <fullName>General site seeing tours</fullName>
            </value>
            <value>
                <fullName>cuisine and culture tours</fullName>
            </value>
            <value>
                <fullName>Wilderness and wildLife</fullName>
            </value>
            <value>
                <fullName>Relaxation and Meditation</fullName>
            </value>
            <value>
                <fullName>Sports</fullName>
            </value>
            <value>
                <fullName>Fashion</fullName>
            </value>
            <value>
                <fullName>Product launch</fullName>
            </value>
            <value>
                <fullName>Beauty</fullName>
            </value>
            <value>
                <fullName>Concert</fullName>
            </value>
            <value>
                <fullName>Festival</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>VIP Airport Transfers</fullName>
            </value>
            <value>
                <fullName>VIP Airport Service / Lounge Access</fullName>
            </value>
            <value>
                <fullName>Airport Meet &amp; Greet</fullName>
            </value>
            <value>
                <fullName>Airport Express Check-In</fullName>
            </value>
            <value>
                <fullName>Transfer service</fullName>
            </value>
            <value>
                <fullName>Private Chauffeurs</fullName>
            </value>
            <value>
                <fullName>Hotel</fullName>
            </value>
            <value>
                <fullName>Beach House</fullName>
            </value>
            <value>
                <fullName>Villa</fullName>
            </value>
            <value>
                <fullName>Apartment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opprtunity_Line_Item_Details__c/fields/Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Sub_Type__c</fullName>
    <label>Sub Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>SubType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opprtunity_Line_Item_Details__c/fields/Time_slot__c.field-meta.xml
<CustomField>
    <fullName>Time_slot__c</fullName>
    <label>Time slot</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Breakfast</fullName>
            </value>
            <value>
                <fullName>Lunch</fullName>
            </value>
            <value>
                <fullName>Dinner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opprtunity_Line_Item_Details__c/fields/Type_of_visa__c.field-meta.xml
<CustomField>
    <fullName>Type_of_visa__c</fullName>
    <label>Type of visa</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Schengen</fullName>
            </value>
            <value>
                <fullName>US</fullName>
            </value>
            <value>
                <fullName>UK</fullName>
            </value>
            <value>
                <fullName>Panama</fullName>
            </value>
            <value>
                <fullName>Papua New Guinea</fullName>
            </value>
            <value>
                <fullName>Paraguay</fullName>
            </value>
            <value>
                <fullName>Peru</fullName>
            </value>
            <value>
                <fullName>Philippines</fullName>
            </value>
            <value>
                <fullName>Poland</fullName>
            </value>
            <value>
                <fullName>Portugal</fullName>
            </value>
            <value>
                <fullName>Sierra Leone</fullName>
            </value>
            <value>
                <fullName>Singapore</fullName>
            </value>
            <value>
                <fullName>Slovakia</fullName>
            </value>
            <value>
                <fullName>Slovenia</fullName>
            </value>
            <value>
                <fullName>Solomon Islands</fullName>
            </value>
            <value>
                <fullName>Tonga</fullName>
            </value>
            <value>
                <fullName>Trinidad and Tobago</fullName>
            </value>
            <value>
                <fullName>Tunisia</fullName>
            </value>
            <value>
                <fullName>Niger</fullName>
            </value>
            <value>
                <fullName>Nigeria</fullName>
            </value>
            <value>
                <fullName>Morocco</fullName>
            </value>
            <value>
                <fullName>Liberia</fullName>
            </value>
            <value>
                <fullName>Libya</fullName>
            </value>
            <value>
                <fullName>Australia and territories</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Service/ServiceService.cls
public  class ServiceService {
    private static ServiceService instance = null;

    private ServiceService() {
    }

    public static ServiceService getInstance() {
        if (instance == null) {
          instance = new ServiceService();
        }
        return instance;
      }

      public Map<String, List<String>> getServiceCategoryList(String type) {
        Map<String, List<String>> categoryMap= DependencyForPicklistApex.getFieldDependencies('Opprtunity_Line_Item_Details__c','Sub_Type__c','Category__c');
        List<String> category = categoryMap.get(type);

        Map<String, List<String>> selectionLists = new Map<String,List<String>>();
        selectionLists.put('Category', category);

        if(type.equals('Visa Management')){
            
         selectionLists.put('Type of Visa', DependencyForPicklistApex.getPickList('Opprtunity_Line_Item_Details__c', 'Type_of_visa__c'));
        }

        if(type.equals('Transport Arrangement - Booking')){
            selectionLists.put('Class', DependencyForPicklistApex.getPickList('Opprtunity_Line_Item_Details__c', 'Class__c'));
            selectionLists.put('Transportation Type', DependencyForPicklistApex.getPickList('Opprtunity_Line_Item_Details__c', 'Transport_Type__c'));
        }
        if(type.equals('Accommodation Management')){
          selectionLists.put('Meal Plan', DependencyForPicklistApex.getPickList('Opprtunity_Line_Item_Details__c', 'Meal_Plan__c'));
          selectionLists.put('Bed size', DependencyForPicklistApex.getPickList('Opprtunity_Line_Item_Details__c', 'Bed_size__c'));
      }
      if(type.equals('Dining & Nightspots Reservations')){
        selectionLists.put('Time slot', DependencyForPicklistApex.getPickList('Opprtunity_Line_Item_Details__c', 'Time_slot__c'));
    }
    if(type.equals('Lifestyle Management')){
      List<Product2> product = [SELECT Name FROM Product2 WHERE Family ='Lifestyle Management Services'];
      List<String> productName = new List<String>();
      for(Product2 p : product){
        productName.add(p.Name);
      }
      selectionLists.put('subType', productName);
    }
       return selectionLists;
   
        }
}