force-app/main/default/objects/Opprtunity_Line_Item_Details__c/Opprtunity_Line_Item_Details__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <label>Opprtunity Line Item Details Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opprtunity_Line_Item_Details__c/fields/Additional_Details__c.field-meta.xml
<CustomField>
    <fullName>Additional_Details__c</fullName>
    <label>Additional Details</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opprtunity_Line_Item_Details__c/fields/Adult__c.field-meta.xml
<CustomField>
    <fullName>Adult__c</fullName>
    <label>Adult</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opprtunity_Line_Item_Details__c/fields/Arival_Date1__c.field-meta.xml
<CustomField>
    <fullName>Arival_Date1__c</fullName>
    <label>Arival Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opprtunity_Line_Item_Details__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Number of Bookings</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opprtunity_Line_Item_Details__c/fields/Cancellation_Policy__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Policy__c</fullName>
    <label>Cancellation Policy</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opprtunity_Line_Item_Details__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sub_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>vaccine</fullName>
            </value>
            <value>
                <fullName>PCR</fullName>
            </value>
            <value>
                <fullName>Honeymoon</fullName>
            </value>
            <value>
                <fullName>Group Travel</fullName>
            </value>
            <value>
                <fullName>Wellness</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Cultural and historical</fullName>
            </value>
            <value>
                <fullName>Water sports</fullName>
            </value>
            <value>
                <fullName>Adventure tours</fullName>
            </value>
            <value>
                <fullName>General site seeing tours</fullName>
            </value>
            <value>
                <fullName>cuisine and culture tours</fullName>
            </value>
            <value>
                <fullName>Wilderness and wildLife</fullName>
            </value>
            <value>
                <fullName>Relaxation and Meditation</fullName>
            </value>
            <value>
                <fullName>Sports</fullName>
            </value>
            <value>
                <fullName>Fashion</fullName>
            </value>
            <value>
                <fullName>Product launch</fullName>
            </value>
            <value>
                <fullName>Beauty</fullName>
            </value>
            <value>
                <fullName>Concert</fullName>
            </value>
            <value>
                <fullName>Festival</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>VIP Airport Transfers</fullName>
            </value>
            <value>
                <fullName>VIP Airport Service / Lounge Access</fullName>
            </value>
            <value>
                <fullName>Airport Meet &amp; Greet</fullName>
            </value>
            <value>
                <fullName>Airport Express Check-In</fullName>
            </value>
            <value>
                <fullName>Transfer service</fullName>
            </value>
            <value>
                <fullName>Private Chauffeurs</fullName>
            </value>
            <value>
                <fullName>Hotel</fullName>
            </value>
            <value>
                <fullName>Beach House</fullName>
            </value>
            <value>
                <fullName>Villa</fullName>
            </value>
            <value>
                <fullName>Apartment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opprtunity_Line_Item_Details__c/fields/Change_Policy__c.field-meta.xml
<CustomField>
    <fullName>Change_Policy__c</fullName>
    <label>Change Policy</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opprtunity_Line_Item_Details__c/fields/Child_0_2yr__c.field-meta.xml
<CustomField>
    <fullName>Child_0_2yr__c</fullName>
    <label>Child 0-2yr</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opprtunity_Line_Item_Details__c/fields/Child_3_12yr__c.field-meta.xml
<CustomField>
    <fullName>Child_3_12yr__c</fullName>
    <label>Child 3-12yr</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opprtunity_Line_Item_Details__c/fields/Citizenship__c.field-meta.xml
<CustomField>
    <fullName>Citizenship__c</fullName>
    <label>Citizenship</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Opprtunity_Line_Item_Details__c/fields/Confirmation_Number__c.field-meta.xml
<CustomField>
    <fullName>Confirmation_Number__c</fullName>
    <label>Confirmation Number</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opprtunity_Line_Item_Details__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunity Line Items Details</relationshipLabel>
    <relationshipName>Opportunity_Line_Items_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opprtunity_Line_Item_Details__c/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <label>Contact Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opprtunity_Line_Item_Details__c/fields/Departure_1__c.field-meta.xml
<CustomField>
    <fullName>Departure_1__c</fullName>
    <label>Departure</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Opprtunity_Line_Item_Details__c/fields/Departure_2__c.field-meta.xml
<CustomField>
    <fullName>Departure_2__c</fullName>
    <label>Departure</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Opprtunity_Line_Item_Details__c/fields/Departure_3__c.field-meta.xml
<CustomField>
    <fullName>Departure_3__c</fullName>
    <label>Departure</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Opprtunity_Line_Item_Details__c/fields/Departure_4__c.field-meta.xml
<CustomField>
    <fullName>Departure_4__c</fullName>
    <label>Departure</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Opprtunity_Line_Item_Details__c/fields/Departure_Date_1__c.field-meta.xml
<CustomField>
    <fullName>Departure_Date_1__c</fullName>
    <label>Departure Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opprtunity_Line_Item_Details__c/fields/Departure_Date_2__c.field-meta.xml
<CustomField>
    <fullName>Departure_Date_2__c</fullName>
    <label>Departure Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opprtunity_Line_Item_Details__c/fields/Departure_Date_3__c.field-meta.xml
<CustomField>
    <fullName>Departure_Date_3__c</fullName>
    <label>Departure Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opprtunity_Line_Item_Details__c/fields/Departure_Date_4__c.field-meta.xml
<CustomField>
    <fullName>Departure_Date_4__c</fullName>
    <label>Departure Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opprtunity_Line_Item_Details__c/fields/Destination_1__c.field-meta.xml
<CustomField>
    <fullName>Destination_1__c</fullName>
    <label>Destination</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Opprtunity_Line_Item_Details__c/fields/Destination_2__c.field-meta.xml
<CustomField>
    <fullName>Destination_2__c</fullName>
    <label>Destination</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Opprtunity_Line_Item_Details__c/fields/Destination_3__c.field-meta.xml
<CustomField>
    <fullName>Destination_3__c</fullName>
    <label>Destination</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Opprtunity_Line_Item_Details__c/fields/Destination_4__c.field-meta.xml
<CustomField>
    <fullName>Destination_4__c</fullName>
    <label>Destination</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Opprtunity_Line_Item_Details__c/fields/Event_Name__c.field-meta.xml
<CustomField>
    <fullName>Event_Name__c</fullName>
    <label>Event Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opprtunity_Line_Item_Details__c/fields/Flight_Number__c.field-meta.xml
<CustomField>
    <fullName>Flight_Number__c</fullName>
    <label>Flight Number</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opprtunity_Line_Item_Details__c/fields/Operation_Details__c.field-meta.xml
<CustomField>
    <fullName>Operation_Details__c</fullName>
    <label>Operation Details</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opprtunity_Line_Item_Details__c/fields/Opportunity_Product__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Product</label>
    <referenceTo>OpportunityLineItem</referenceTo>
    <relationshipLabel>Opportunity Line Items Details</relationshipLabel>
    <relationshipName>Opportunity_Line_Items_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opprtunity_Line_Item_Details__c/fields/Prefrence__c.field-meta.xml
<CustomField>
    <fullName>Prefrence__c</fullName>
    <label>preferences</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opprtunity_Line_Item_Details__c/fields/Promo_code__c.field-meta.xml
<CustomField>
    <fullName>Promo_code__c</fullName>
    <label>Promo code</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opprtunity_Line_Item_Details__c/fields/Request_Details__c.field-meta.xml
<CustomField>
    <fullName>Request_Details__c</fullName>
    <label>Request Details</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opprtunity_Line_Item_Details__c/fields/Room__c.field-meta.xml
<CustomField>
    <fullName>Room__c</fullName>
    <label>Room occupancy</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opprtunity_Line_Item_Details__c/fields/Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Sub_Type__c</fullName>
    <label>Sub Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>SubType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opprtunity_Line_Item_Details__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Supplier</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Opprtunity_Line_Items_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opprtunity_Line_Item_Details__c/fields/Ticket_Type__c.field-meta.xml
<CustomField>
    <fullName>Ticket_Type__c</fullName>
    <label>Ticket Type</label>
    <length>130000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opprtunity_Line_Item_Details__c/fields/Time_slot__c.field-meta.xml
<CustomField>
    <fullName>Time_slot__c</fullName>
    <label>Time slot</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Breakfast</fullName>
            </value>
            <value>
                <fullName>Lunch</fullName>
            </value>
            <value>
                <fullName>Dinner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opprtunity_Line_Item_Details__c/fields/Trip_type__c.field-meta.xml
<CustomField>
    <fullName>Trip_type__c</fullName>
    <label>Trip type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>One-way</fullName>
            </value>
            <value>
                <fullName>RoundTrip</fullName>
            </value>
            <value>
                <fullName>Multi-city</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opprtunity_Line_Item_Details__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Request_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Request_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Travel Services</fullName>
    </customValue>
    <customValue>
        <fullName>Concierge Services</fullName>
    </customValue>
    <customValue>
        <fullName>Lifestyle Management Services</fullName>
    </customValue>
    <masterLabel>Request Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Repository/ServiceRepository.cls
public class ServiceRepository {
private static ServiceRepository instance = null;

    public ServiceRepository() {

    }

    public static ServiceRepository getInstance() {
        if (instance == null) {
          instance = new ServiceRepository();
        }
        return instance;
      }

    public Opprtunity_Line_Item_Details__c findAllService(){

        return [
          SELECT
          Id,
          Name,
          Additional_Details__c,
          Adult__c,
          Airline__c,
          Arival_Date__c,
          Arival_Date1__c,
          Bed_size__c,
          Cancellation_Policy__c,
          Category__c,
          Change_Policy__c,
          Child_0_2yr__c,
          Child_3_12yr__c,
          Citizenship__c,
          Class__c,
          Confirmation_Number__c,
          Contact__c,
          Contact_Name__c,
          Contact_Number__c,
          Departure_1__c,
          Departure_2__c,
          Departure_3__c,
          Departure_4__c,
          Departure__c,
          Departure_Date_2__c,
          Departure_Date_3__c,
          Departure_Date_4__c,
          Departure_Date_1__c,
          Departure_Date__c,
          Destination_1__c,
          Destination_2__c,
          Destination_3__c,
          Destination_4__c,
          Destination__c,
          Event_Name__c,
          Flight_Number__c,
          Hotel__c,
          Meal_Plan__c,
          Booking__c,
          Operation_Details__c,
          Opportunity_Product__c,
          Prefrence__c,
          Promo_code__c,
          Request_Details__c,
          Room__c,
          Sub_Type__c,
          Supplier__c,
          Ticket_Type__c,
          Time_slot__c,
          Transport_Type__c,
          Trip_type__c,
          Type__c,
          Type_of_visa__c,
          Venu__c
          FROM Opprtunity_Line_Item_Details__c
          ];
    }
          public List<Opprtunity_Line_Item_Details__c> findServiceByOpportunityProduct(List<String> opportunityProductId){

            return [
              SELECT
              Id,
              Name,
              Additional_Details__c,
              Adult__c,
              Airline__c,
              Arival_Date__c,
              Arival_Date1__c,
              Bed_size__c,
              Cancellation_Policy__c,
              Category__c,
              Change_Policy__c,
              Child_0_2yr__c,
              Child_3_12yr__c,
              Citizenship__c,
              Class__c,
              Confirmation_Number__c,
              Contact__c,
              Contact_Name__c,
              Contact_Number__c,
              Departure_1__c,
              Departure_2__c,
              Departure_3__c,
              Departure_4__c,
              Departure__c,
              Departure_Date_2__c,
              Departure_Date_3__c,
              Departure_Date_4__c,
              Departure_Date_1__c,
              Departure_Date__c,
              Destination_1__c,
              Destination_2__c,
              Destination_3__c,
              Destination_4__c,
              Destination__c,
              Event_Name__c,
              Flight_Number__c,
              Hotel__c,
              Meal_Plan__c,
              Booking__c,
              Operation_Details__c,
              Opportunity_Product__c,
              Prefrence__c,
              Promo_code__c,
              Request_Details__c,
              Room__c,
              Sub_Type__c,
              Supplier__c,
              Ticket_Type__c,
              Time_slot__c,
              Transport_Type__c,
              Trip_type__c,
              Type__c,
              Type_of_visa__c,
              Venu__c
              FROM Opprtunity_Line_Item_Details__c
              WHERE Opportunity_Product__c = :opportunityProductId	
              ];
          

    }

}