force-app/main/default/objects/Opprtunity_Line_Item_Details__c/Opprtunity_Line_Item_Details__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <label>Opprtunity Line Item Details Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opprtunity_Line_Item_Details__c/fields/Airline2__c.field-meta.xml
<CustomField>
    <fullName>Airline2__c</fullName>
    <label>Airline</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Opprtunity_Line_Item_Details__c/fields/Airline4__c.field-meta.xml
<CustomField>
    <fullName>Airline4__c</fullName>
    <label>Airline</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Opprtunity_Line_Item_Details__c/fields/Arival_Date1__c.field-meta.xml
<CustomField>
    <fullName>Arival_Date1__c</fullName>
    <label>Arival Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opprtunity_Line_Item_Details__c/fields/Catalogue__c.field-meta.xml
<CustomField>
    <fullName>Catalogue__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Catalogue</label>
    <referenceTo>Catalogue__c</referenceTo>
    <relationshipLabel>Opportunity Line Items Details</relationshipLabel>
    <relationshipName>Opportunity_Line_Items_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opprtunity_Line_Item_Details__c/fields/Event_Name__c.field-meta.xml
<CustomField>
    <fullName>Event_Name__c</fullName>
    <label>Event Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opprtunity_Line_Item_Details__c/fields/Room__c.field-meta.xml
<CustomField>
    <fullName>Room__c</fullName>
    <label>Room occupancy</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opprtunity_Line_Item_Details__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Supplier</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Opprtunity_Line_Items_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opprtunity_Line_Item_Details__c/fields/Trip_type__c.field-meta.xml
<CustomField>
    <fullName>Trip_type__c</fullName>
    <label>Trip type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>One-way</fullName>
            </value>
            <value>
                <fullName>RoundTrip</fullName>
            </value>
            <value>
                <fullName>Multi-city</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote_Line_Item_Detail__c/Quote_Line_Item_Detail__c.object-meta.xml
<CustomObject>
    <label>Quote Line Item Detail</label>
    <nameField>
        <label>Quote Line Item Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Line Items Detail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote_Line_Item_Detail__c/fields/Airline1__c.field-meta.xml
<CustomField>
    <fullName>Airline1__c</fullName>
    <label>Airline</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item_Detail__c/fields/Airline3__c.field-meta.xml
<CustomField>
    <fullName>Airline3__c</fullName>
    <label>Airline</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item_Detail__c/fields/Airline__c.field-meta.xml
<CustomField>
    <fullName>Airline__c</fullName>
    <label>Airline</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item_Detail__c/fields/Airport__c.field-meta.xml
<CustomField>
    <fullName>Airport__c</fullName>
    <label>Airport</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item_Detail__c/fields/Arival_Date2__c.field-meta.xml
<CustomField>
    <fullName>Arival_Date2__c</fullName>
    <label>Arival Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item_Detail__c/fields/Arival_Date3__c.field-meta.xml
<CustomField>
    <fullName>Arival_Date3__c</fullName>
    <label>Arival Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item_Detail__c/fields/Arival_Date4__c.field-meta.xml
<CustomField>
    <fullName>Arival_Date4__c</fullName>
    <label>Arival Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item_Detail__c/fields/Arival_Date__c.field-meta.xml
<CustomField>
    <fullName>Arival_Date__c</fullName>
    <label>Arival Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item_Detail__c/fields/Bed_size__c.field-meta.xml
<CustomField>
    <fullName>Bed_size__c</fullName>
    <label>Bed size</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>King</fullName>
            </value>
            <value>
                <fullName>Double</fullName>
            </value>
            <value>
                <fullName>Single</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote_Line_Item_Detail__c/fields/Bookings__c.field-meta.xml
<CustomField>
    <fullName>Bookings__c</fullName>
    <label>Number of Bookings</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item_Detail__c/fields/Class1__c.field-meta.xml
<CustomField>
    <fullName>Class1__c</fullName>
    <label>Class</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Class</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote_Line_Item_Detail__c/fields/Class2__c.field-meta.xml
<CustomField>
    <fullName>Class2__c</fullName>
    <label>Class</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Class</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote_Line_Item_Detail__c/fields/Class3__c.field-meta.xml
<CustomField>
    <fullName>Class3__c</fullName>
    <label>Class</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Class</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote_Line_Item_Detail__c/fields/Class4__c.field-meta.xml
<CustomField>
    <fullName>Class4__c</fullName>
    <label>Class</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Class</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote_Line_Item_Detail__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>Class</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Class</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote_Line_Item_Detail__c/fields/Departure1__c.field-meta.xml
<CustomField>
    <fullName>Departure1__c</fullName>
    <label>Departure</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item_Detail__c/fields/Departure2__c.field-meta.xml
<CustomField>
    <fullName>Departure2__c</fullName>
    <label>Departure</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item_Detail__c/fields/Departure3__c.field-meta.xml
<CustomField>
    <fullName>Departure3__c</fullName>
    <label>Departure</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item_Detail__c/fields/Departure4__c.field-meta.xml
<CustomField>
    <fullName>Departure4__c</fullName>
    <label>Departure</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item_Detail__c/fields/Departure__c.field-meta.xml
<CustomField>
    <fullName>Departure__c</fullName>
    <label>Departure</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item_Detail__c/fields/Departure_Date1__c.field-meta.xml
<CustomField>
    <fullName>Departure_Date1__c</fullName>
    <label>Departure Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item_Detail__c/fields/Departure_Date2__c.field-meta.xml
<CustomField>
    <fullName>Departure_Date2__c</fullName>
    <label>Departure Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item_Detail__c/fields/Departure_Date3__c.field-meta.xml
<CustomField>
    <fullName>Departure_Date3__c</fullName>
    <label>Departure Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item_Detail__c/fields/Departure_Date4__c.field-meta.xml
<CustomField>
    <fullName>Departure_Date4__c</fullName>
    <label>Departure Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item_Detail__c/fields/Departure_Date__c.field-meta.xml
<CustomField>
    <fullName>Departure_Date__c</fullName>
    <label>Departure Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item_Detail__c/fields/Destination1__c.field-meta.xml
<CustomField>
    <fullName>Destination1__c</fullName>
    <label>Destination</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item_Detail__c/fields/Destination2__c.field-meta.xml
<CustomField>
    <fullName>Destination2__c</fullName>
    <label>Destination</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item_Detail__c/fields/Destination3__c.field-meta.xml
<CustomField>
    <fullName>Destination3__c</fullName>
    <label>Destination</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item_Detail__c/fields/Destination4__c.field-meta.xml
<CustomField>
    <fullName>Destination4__c</fullName>
    <label>Destination</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item_Detail__c/fields/Destination__c.field-meta.xml
<CustomField>
    <fullName>Destination__c</fullName>
    <label>Destination</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item_Detail__c/fields/Event_Name__c.field-meta.xml
<CustomField>
    <fullName>Event_Name__c</fullName>
    <label>Event Name</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item_Detail__c/fields/Hotel__c.field-meta.xml
<CustomField>
    <fullName>Hotel__c</fullName>
    <label>Hotel</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item_Detail__c/fields/Meal_Plan__c.field-meta.xml
<CustomField>
    <fullName>Meal_Plan__c</fullName>
    <label>Meal Plan</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Meal_Plan</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote_Line_Item_Detail__c/fields/Opportunity_Line_Item_Details__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Line_Item_Details__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Line Item Details</label>
    <referenceTo>Opprtunity_Line_Item_Details__c</referenceTo>
    <relationshipLabel>Quote Line Items Detail</relationshipLabel>
    <relationshipName>Quote_Line_Items_Detail</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item_Detail__c/fields/Preferences__c.field-meta.xml
<CustomField>
    <fullName>Preferences__c</fullName>
    <label>Preferences</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item_Detail__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Quote Line Items Detail</relationshipLabel>
    <relationshipName>Quote_Line_Items_Detail</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item_Detail__c/fields/Sales_Price__c.field-meta.xml
<CustomField>
    <fullName>Sales_Price__c</fullName>
    <label>Sales Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item_Detail__c/fields/Service_Name__c.field-meta.xml
<CustomField>
    <fullName>Service_Name__c</fullName>
    <formula>TEXT(Opportunity_Line_Item_Details__r.Sub_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Service Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item_Detail__c/fields/SubType__c.field-meta.xml
<CustomField>
    <fullName>SubType__c</fullName>
    <formula>Text(Opportunity_Line_Item_Details__r.Sub_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SubType</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item_Detail__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Supplier</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quote Line Items Detail</relationshipLabel>
    <relationshipName>Quote_Line_Items_Detail</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item_Detail__c/fields/Transport_Type__c.field-meta.xml
<CustomField>
    <fullName>Transport_Type__c</fullName>
    <label>Transport Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Transport_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Class.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Economy</fullName>
    </customValue>
    <customValue>
        <fullName>First</fullName>
    </customValue>
    <customValue>
        <fullName>Business</fullName>
    </customValue>
    <masterLabel>Class</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Meal_Plan.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Breakfast</fullName>
    </customValue>
    <customValue>
        <fullName>Half board</fullName>
    </customValue>
    <customValue>
        <fullName>Full board</fullName>
    </customValue>
    <masterLabel>Meal Plan</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Transport_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Car</fullName>
    </customValue>
    <customValue>
        <fullName>Train</fullName>
    </customValue>
    <customValue>
        <fullName>Bus</fullName>
    </customValue>
    <customValue>
        <fullName>Boat</fullName>
    </customValue>
    <masterLabel>Transport Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Repository/QuoteLineItemDetailRepository.cls
public class QuoteLineItemDetailRepository {
    private static QuoteLineItemDetailRepository instance = null;
    private QuoteLineItemDetailRepository(){}

    public static QuoteLineItemDetailRepository getInstance() {
        if (instance == null) {
          instance = new QuoteLineItemDetailRepository();
        }
        return instance;
      }
      public List<Quote_Line_Item_Detail__c> findAllQuoteLineItemDetails(){
        return [
            SELECT
            Airline__c,
            Airline2__c,
            Airline4__c,
            Airline1__c,
            Airline3__c,
            Airport__c,
            Arival_Date__c,
            Arival_Date4__c,
            Arival_Date1__c,
            Arival_Date2__c,
            Arival_Date3__c,
            Bed_size__c,
            Catalogue__c,
            Class__c,
            Class1__c,
            Class2__c,
            Class3__c,
            Class4__c,
            Departure__c,
            Departure1__c,
            Departure2__c,
            Departure3__c,
            Departure4__c,
            Departure_Date__c,
            Departure_Date1__c,
            Departure_Date2__c,
            Departure_Date3__c,
            Departure_Date4__c,
            Description__c,
            Destination__c,
            Destination1__c,
            Destination2__c,
            Destination3__c,
            Destination4__c,
            Event_Name__c,
            Hotel__c,
            List_Price__c,
            Meal_Plan__c,
            Bookings__c,
            Opportunity_Line_Item_Details__c,
            Preferences__c,
            Quote__c,
            Name,
            Room__c,
            Sales_Price__c,
            Service_Name__c,
            SubType__c,
            Supplier__c,
            Transport_Type__c,
            Trip_type__c,
            Venu__c
            FROM Quote_Line_Item_Detail__c
        ];
      }

      public List<Quote_Line_Item_Detail__c> findQuoteLineItemDetailBy(Id opportunityLineItemDetails){
        return [
            SELECT
            Airline__c,
            Airline2__c,
            Airline4__c,
            Airline1__c,
            Airline3__c,
            Airport__c,
            Arival_Date__c,
            Arival_Date4__c,
            Arival_Date1__c,
            Arival_Date2__c,
            Arival_Date3__c,
            Bed_size__c,
            Catalogue__c,
            Class__c,
            Class1__c,
            Class2__c,
            Class3__c,
            Class4__c,
            Departure__c,
            Departure1__c,
            Departure2__c,
            Departure3__c,
            Departure4__c,
            Departure_Date__c,
            Departure_Date1__c,
            Departure_Date2__c,
            Departure_Date3__c,
            Departure_Date4__c,
            Description__c,
            Destination__c,
            Destination1__c,
            Destination2__c,
            Destination3__c,
            Destination4__c,
            Event_Name__c,
            Hotel__c,
            List_Price__c,
            Meal_Plan__c,
            Bookings__c,
            Opportunity_Line_Item_Details__r.Category__c,
            Preferences__c,
            Quote__c,
            Name,
            Room__c,
            Sales_Price__c,
            Service_Name__c,
            SubType__c,
            Supplier__c,
            Transport_Type__c,
            Trip_type__c,
            Venu__c,
            Opportunity_Line_Item_Details__c
            FROM Quote_Line_Item_Detail__c
            WHERE Opportunity_Line_Item_Details__c =:opportunityLineItemDetails
        ];
      }
}