force-app/main/default/objects/Opprtunity_Line_Item_Details__c/Opprtunity_Line_Item_Details__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <label>Opprtunity Line Item Details Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opprtunity_Line_Item_Details__c/fields/Opportunity_Product__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Product</label>
    <referenceTo>OpportunityLineItem</referenceTo>
    <relationshipLabel>Opportunity Line Items Details</relationshipLabel>
    <relationshipName>Opportunity_Line_Items_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Mapper/ServiceMapper.cls
global class ServiceMapper {
    String serviceName;
    String destination;
    List<String> logo;

    public ServiceMapper() {

    }

    public ServiceMapper ServiceobjectToMapper( Opprtunity_Line_Item_Details__c servicesObject , String logo){
        
        ServiceMapper serviceMapper = new ServiceMapper();
        ImageListMapper ImageListMapperInstance = ImageListMapper.getInstance();
        serviceMapper.serviceName = servicesObject.Name;
        serviceMapper.destination = servicesObject.Destination__c;
        ServiceMapper.logo = ImageListMapperInstance.ConvertToImageList(logo);
        

      return serviceMapper;
    }


    public  List<ServiceMapper> ServiceobjectListToMapperList(List<Opprtunity_Line_Item_Details__c> servicesObjectList , Map<String,String> logoMap){

        List<ServiceMapper> mapperList = new List<ServiceMapper>();

        for( Opprtunity_Line_Item_Details__c c : servicesObjectList ){
            
            mapperList.add(ServiceobjectToMapper(c ,logoMap.get(c.Opportunity_Product__c)));
        }

        return mapperList;
      }
}