force-app/main/default/objects/Preference__c/Preference__c.object-meta.xml
<CustomObject>
    <label>Preference</label>
    <nameField>
        <label>Preference Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Preferences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Preference__c/fields/Main_Tag__c.field-meta.xml
<CustomField>
    <fullName>Main_Tag__c</fullName>
    <label>Main Tag</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tags</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Tags.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Entertainment</fullName>
    </customValue>
    <customValue>
        <fullName>Adventure</fullName>
    </customValue>
    <customValue>
        <fullName>Wellness</fullName>
    </customValue>
    <customValue>
        <fullName>Recreation</fullName>
    </customValue>
    <customValue>
        <fullName>Business</fullName>
    </customValue>
    <customValue>
        <fullName>Travel</fullName>
    </customValue>
    <customValue>
        <fullName>General</fullName>
    </customValue>
    <description>Main tags category</description>
    <masterLabel>Tags</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Service/PreferenceService.cls
public with sharing class PreferenceService {
    private static PreferenceService instance = null;
    public  PreferenceRepository preferenceRepositoryInstance;
    public  ContactRepository contactRepositoryInstance;
    private PreferenceService() {
       preferenceRepositoryInstance = PreferenceRepository.getInstance();
       contactRepositoryInstance = ContactRepository.getInstance();
    }

    public static PreferenceService getInstance() {
        if (instance == null) {
          instance = new PreferenceService();
        }
        return instance;
      }

    public List<String> getMainTagsList() {
       
        List<String> tagslist = new List<String>();
       
        Schema.DescribeFieldResult fieldResult = preference__c.Main_Tag__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
         for( Schema.PicklistEntry f : ple)
        {
            tagslist.add(f.getLabel());
        }     
    
        return tagslist;
    
    }
    public List<String> getContactMainTagsList(String Id , String app) {
        List<String> tagslist = new List<String>();
        List<preference__c>  preferences ;
        if(app.equals('orange')){
        preferences = preferenceRepositoryInstance.findByContact(contactRepositoryInstance.findByOrangeId(Id));
        }else{
        preferences = preferenceRepositoryInstance.findByContact(contactRepositoryInstance.findByRecordId(Id));
        }
        for( preference__c p : preferences)
        {
            if (!(tagslist.contains(p.Main_Tag__c))){
            tagslist.add(p.Main_Tag__c);}
        }   

        return tagslist;
    }

}