force-app/main/default/objects/Preference__c/Preference__c.object-meta.xml
<CustomObject>
    <label>Preference</label>
    <nameField>
        <label>Preference Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Preferences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Preference__c/fields/Main_Tag__c.field-meta.xml
<CustomField>
    <fullName>Main_Tag__c</fullName>
    <label>Main Tag</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tags</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Preference__c/fields/Sub_Tags__c.field-meta.xml
<CustomField>
    <fullName>Sub_Tags__c</fullName>
    <label>Sub Tags</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Main_Tag__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Sub_Tags</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Sub_Tags.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Concerts</fullName>
    </customValue>
    <customValue>
        <fullName>Music Festivals</fullName>
    </customValue>
    <customValue>
        <fullName>Fashion Shows</fullName>
    </customValue>
    <customValue>
        <fullName>Opera</fullName>
    </customValue>
    <customValue>
        <fullName>Theatre</fullName>
    </customValue>
    <customValue>
        <fullName>Art &amp; Antique Fairs</fullName>
    </customValue>
    <customValue>
        <fullName>Water Sports</fullName>
    </customValue>
    <customValue>
        <fullName>Sports</fullName>
    </customValue>
    <customValue>
        <fullName>Sightseeing</fullName>
    </customValue>
    <customValue>
        <fullName>Wilderness &amp; Wildlife</fullName>
    </customValue>
    <customValue>
        <fullName>Desert Safari</fullName>
    </customValue>
    <customValue>
        <fullName>Cups &amp; Championships</fullName>
    </customValue>
    <customValue>
        <fullName>Meditation</fullName>
    </customValue>
    <customValue>
        <fullName>Relaxation</fullName>
    </customValue>
    <customValue>
        <fullName>Beauty</fullName>
    </customValue>
    <customValue>
        <fullName>Fitness</fullName>
    </customValue>
    <customValue>
        <fullName>Wellness Festivals</fullName>
    </customValue>
    <customValue>
        <fullName>Spirituality</fullName>
    </customValue>
    <customValue>
        <fullName>Rejuvenation</fullName>
    </customValue>
    <customValue>
        <fullName>Cuisine</fullName>
    </customValue>
    <customValue>
        <fullName>Culture</fullName>
    </customValue>
    <customValue>
        <fullName>History</fullName>
    </customValue>
    <customValue>
        <fullName>Social Happenings</fullName>
    </customValue>
    <customValue>
        <fullName>Seasonal Celebrations</fullName>
    </customValue>
    <customValue>
        <fullName>Family</fullName>
    </customValue>
    <customValue>
        <fullName>Business Travel</fullName>
    </customValue>
    <customValue>
        <fullName>Entrepreneurship</fullName>
    </customValue>
    <customValue>
        <fullName>Trade Shows &amp; Expos</fullName>
    </customValue>
    <customValue>
        <fullName>Incentive Trips &amp; Company Retreats</fullName>
    </customValue>
    <customValue>
        <fullName>Conferences &amp; Events</fullName>
    </customValue>
    <masterLabel>Sub-Tags</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Tags.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Entertainment</fullName>
    </customValue>
    <customValue>
        <fullName>Adventure</fullName>
    </customValue>
    <customValue>
        <fullName>Wellness</fullName>
    </customValue>
    <customValue>
        <fullName>Recreation</fullName>
    </customValue>
    <customValue>
        <fullName>Business</fullName>
    </customValue>
    <customValue>
        <fullName>Travel</fullName>
    </customValue>
    <customValue>
        <fullName>General</fullName>
    </customValue>
    <description>Main tags category</description>
    <masterLabel>Tags</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Repository/PreferenceRepository.cls
public with sharing class PreferenceRepository {
    private static PreferenceRepository instance = null;

    public PreferenceRepository() {}
    public static PreferenceRepository getInstance() {
        if (instance == null) {
          instance = new PreferenceRepository();
        }
        return instance;
      }

      public List<preference__c> findByContact(Contact contact) {

        return [
          SELECT
          Main_Tag__c,
          Sub_Tags__c
          FROM preference__c
          WHERE Contact__c = :contact.Id
          ];
      }

      public List<preference__c> findAllPrefernces() {

        return [
          SELECT
          Main_Tag__c,
          Sub_Tags__c
          FROM preference__c
          ];
      }
}