force-app/main/default/objects/Company_Info__mdt/Company_Info__mdt.object-meta.xml
<CustomObject>
    <label>Company Info</label>
    <pluralLabel>Company Infos</pluralLabel>
</CustomObject>

force-app/main/default/objects/Company_Info__mdt/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Company_Info__mdt/fields/License_No__c.field-meta.xml
<CustomField>
    <fullName>License_No__c</fullName>
    <label>License No</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Company_Info__mdt/fields/Reg_No__c.field-meta.xml
<CustomField>
    <fullName>Reg_No__c</fullName>
    <label>Reg No</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Company_Info__mdt/fields/Tax_ID__c.field-meta.xml
<CustomField>
    <fullName>Tax_ID__c</fullName>
    <label>Tax ID</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/Mapper/CompanyInfoMapper.cls
global class CompanyInfoMapper {
String address;
String email;
String licenseNo;
String phone;
String regNo;
String taxID;
String url;
    public CompanyInfoMapper() {

    }

    public CompanyInfoMapper CompanyInfoMapper(Company_Info__mdt companyInfo){
        CompanyInfoMapper companyInfoMapper= new CompanyInfoMapper();
        companyInfoMapper.address = companyInfo.Address__c;
        companyInfoMapper.email = companyInfo.Email__c;
        companyInfoMapper.licenseNo = companyInfo.License_No__c;
        companyInfoMapper.phone = companyInfo.Phone__c;
        companyInfoMapper.regNo = companyInfo.Reg_No__c;
        companyInfoMapper.taxID =companyInfo.Tax_ID__c;

        return companyInfoMapper;
    }
}