force-app/main/default/objects/Company_Info__mdt/Company_Info__mdt.object-meta.xml
<CustomObject>
    <label>Company Info</label>
    <pluralLabel>Company Infos</pluralLabel>
</CustomObject>

force-app/main/default/objects/Company_Info__mdt/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Company_Info__mdt/fields/License_No__c.field-meta.xml
<CustomField>
    <fullName>License_No__c</fullName>
    <label>License No</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Company_Info__mdt/fields/Reg_No__c.field-meta.xml
<CustomField>
    <fullName>Reg_No__c</fullName>
    <label>Reg No</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Company_Info__mdt/fields/Tax_ID__c.field-meta.xml
<CustomField>
    <fullName>Tax_ID__c</fullName>
    <label>Tax ID</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Company_Info__mdt/fields/Url__c.field-meta.xml
<CustomField>
    <fullName>Url__c</fullName>
    <label>Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/Repository/CustomMetadataRepository.cls
/**
 * @description       : 
 * @author            : Mohamed Tarek
 * @group             : 
 * @last modified on  : 02-21-2023
 * @last modified by  : Mohamed Tarek
**/
public class CustomMetadataRepository {
    private static CustomMetadataRepository instance = null;

    public CustomMetadataRepository() {

    }
    public static CustomMetadataRepository getInstance() {
        if (instance == null) {
          instance = new CustomMetadataRepository();
        }
        return instance;
      }

    public Company_Info__mdt getCompanyInfo() {
    return [
        SELECT 
        Address__c,
        Email__c,
        License_No__c,
        Phone__c,
        Reg_No__c,
        Tax_ID__c,
        Url__c 
        from Company_Info__mdt]; 
    }
    public Firebase_Credential__mdt getFirebaseCredentials(){
      return [
        SELECT
        API_Key__c
        FROM
        Firebase_Credential__mdt
        WHERE
        Label='Credentials'

      ];
    }
}