force-app/main/default/objects/Catalogue_Photos__c/Catalogue_Photos__c.object-meta.xml
<CustomObject>
    <label>Photos &amp; Links</label>
    <nameField>
        <label>Collection Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Photos  &amp; Links</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Catalogue_Photos__c/fields/thumbnail_Image__c.field-meta.xml
<CustomField>
    <fullName>thumbnail_Image__c</fullName>
    <label>thumbnail Image</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Catalogue_Photos__c/fields/Video_Link__c.field-meta.xml
<CustomField>
    <fullName>Video_Link__c</fullName>
    <label>Video Link</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/classes/Mapper/VideoMapper.cls
global class VideoMapper {
    String name;
    String thumbnailImage;
    String videoLink;

    public VideoMapper() {

    }
    public VideoMapper convertVideo(Catalogue_Photos__c videoCatalogue){
        ImageListMapper ImageListMapperInstance = ImageListMapper.getInstance(); 
        VideoMapper videoMapper = new VideoMapper();
        videoMapper.name = videoCatalogue.Name;
        videoMapper.thumbnailImage = ImageListMapperInstance.ConvertToImageList(videoCatalogue.thumbnail_Image__c).get(0);
        videoMapper.videoLink = videoCatalogue.Video_Link__c;
        return videoMapper;
    }
    public List<VideoMapper> convertVideos(List<Catalogue_Photos__c> videoCatalogues){
        List<VideoMapper> videoMap = new List<VideoMapper>();
        for(Catalogue_Photos__c v :videoCatalogues ){
            videoMap.add(convertVideo(v));
        }

        return videoMap;
    }
}