force-app/main/default/objects/Account/fields/Balance__c.field-meta.xml
<CustomField>
    <fullName>Balance__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Balance</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Consumed__c.field-meta.xml
<CustomField>
    <fullName>Consumed__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Consumed</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Guest__c.field-meta.xml
<CustomField>
    <fullName>Guest__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Guest</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Plan__c.field-meta.xml
<CustomField>
    <fullName>Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plan</label>
    <referenceTo>Plan__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Total_Hold__c.field-meta.xml
<CustomField>
    <fullName>Total_Hold__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Hold</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Plan__c/Plan__c.object-meta.xml
<CustomObject>
    <label>Plan</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Repository/AccountRepository.cls
public class AccountRepository {
  
    private static AccountRepository instance = null;
    private AccountRepository() {}

    public static AccountRepository getInstance() {
        if (instance == null) {
          instance = new AccountRepository();
        }
        return instance;
     
     }  

     public Account findByAccountId(String accountId){

        return [
            SELECT
            Name,
            Balance__c,
            Consumed__c,
            Plan__c,
            Total_Hold__c,
            Guest__c
            FROM Account
            WHERE Id = :accountId
            ];
  
     }

}