force-app/main/default/objects/Account/fields/Plan__c.field-meta.xml
<CustomField>
    <fullName>Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plan</label>
    <referenceTo>Plan__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Plan__c.field-meta.xml
<CustomField>
    <fullName>Plan__c</fullName>
    <label>Plan</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tier</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Reservation.recordType-meta.xml
<RecordType>
    <fullName>Reservation</fullName>
    <active>true</active>
    <businessProcess>Reservation</businessProcess>
    <label>Reservation</label>
</RecordType>

force-app/main/default/objects/Catalogue__c/Catalogue__c.object-meta.xml
<CustomObject>
    <label>Catalogue</label>
    <nameField>
        <label>Catalogue Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Catalogues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Catalogue__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>City</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Catalogue__c/fields/City_Guide__c.field-meta.xml
<CustomField>
    <fullName>City_Guide__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>City Guide</label>
    <referenceTo>City_Guide__c</referenceTo>
    <relationshipLabel>Catalogues</relationshipLabel>
    <relationshipName>Catalogues</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Catalogue__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hotel</fullName>
            </value>
            <value>
                <fullName>Villa</fullName>
            </value>
            <value>
                <fullName>Store</fullName>
            </value>
            <value>
                <fullName>Musem</fullName>
            </value>
            <value>
                <fullName>Yacht</fullName>
            </value>
            <value>
                <fullName>Car</fullName>
            </value>
            <value>
                <fullName>Beach Club</fullName>
            </value>
            <value>
                <fullName>Night Spot</fullName>
            </value>
            <value>
                <fullName>Fine Dinning</fullName>
            </value>
            <value>
                <fullName>Casual Dinning</fullName>
            </value>
            <value>
                <fullName>Airline</fullName>
            </value>
            <value>
                <fullName>Private Jet</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/City_Guide__c/City_Guide__c.object-meta.xml
<CustomObject>
    <label>City Guide</label>
    <nameField>
        <label>City Guide Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>City Guides</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/City_Guide__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/City_Guide__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <label>Duration (Days)</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Password</label>
    <length>20</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Contact/fields/UserName__c.field-meta.xml
<CustomField>
    <fullName>UserName__c</fullName>
    <externalId>true</externalId>
    <label>Username</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact_City_Guide__c/Contact_City_Guide__c.object-meta.xml
<CustomObject>
    <label>Contact City Guide</label>
    <nameField>
        <displayFormat>City Guide -{000}</displayFormat>
        <label>Contact City Guide Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact City Guide</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_City_Guide__c/fields/City_Guide__c.field-meta.xml
<CustomField>
    <fullName>City_Guide__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>City Guide</label>
    <referenceTo>City_Guide__c</referenceTo>
    <relationshipLabel>Contact City Guide</relationshipLabel>
    <relationshipName>Contact_City_Guide</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact_City_Guide__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>City Guide</relationshipLabel>
    <relationshipName>Contact_City_Guide</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Membership__c/Membership__c.object-meta.xml
<CustomObject>
    <label>Membership</label>
    <nameField>
        <label>Membership ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Memberships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Membership__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Memberships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Membership__c/fields/MemberShip_Provider__c.field-meta.xml
<CustomField>
    <fullName>MemberShip_Provider__c</fullName>
    <label>Membership Provider</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Membership__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Password</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opprtunity_Line_Item_Details__c/Opprtunity_Line_Item_Details__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <label>Opprtunity Line Item Details Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opprtunity_Line_Item_Details__c/fields/Catalogue__c.field-meta.xml
<CustomField>
    <fullName>Catalogue__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Catalogue</label>
    <referenceTo>Catalogue__c</referenceTo>
    <relationshipLabel>Opportunity Line Items Details</relationshipLabel>
    <relationshipName>Opportunity_Line_Items_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opprtunity_Line_Item_Details__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sub_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>vaccine</fullName>
            </value>
            <value>
                <fullName>PCR</fullName>
            </value>
            <value>
                <fullName>Honeymoon</fullName>
            </value>
            <value>
                <fullName>Group Travel</fullName>
            </value>
            <value>
                <fullName>Wellness</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Cultural and historical</fullName>
            </value>
            <value>
                <fullName>Water sports</fullName>
            </value>
            <value>
                <fullName>Adventure tours</fullName>
            </value>
            <value>
                <fullName>General site seeing tours</fullName>
            </value>
            <value>
                <fullName>cuisine and culture tours</fullName>
            </value>
            <value>
                <fullName>Wilderness and wildLife</fullName>
            </value>
            <value>
                <fullName>Relaxation and Meditation</fullName>
            </value>
            <value>
                <fullName>Sports</fullName>
            </value>
            <value>
                <fullName>Fashion</fullName>
            </value>
            <value>
                <fullName>Product launch</fullName>
            </value>
            <value>
                <fullName>Beauty</fullName>
            </value>
            <value>
                <fullName>Concert</fullName>
            </value>
            <value>
                <fullName>Festival</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>VIP Airport Transfers</fullName>
            </value>
            <value>
                <fullName>VIP Airport Service / Lounge Access</fullName>
            </value>
            <value>
                <fullName>Airport Meet &amp; Greet</fullName>
            </value>
            <value>
                <fullName>Airport Express Check-In</fullName>
            </value>
            <value>
                <fullName>Transfer service</fullName>
            </value>
            <value>
                <fullName>Private Chauffeurs</fullName>
            </value>
            <value>
                <fullName>Hotel</fullName>
            </value>
            <value>
                <fullName>Beach House</fullName>
            </value>
            <value>
                <fullName>Villa</fullName>
            </value>
            <value>
                <fullName>Apartment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opprtunity_Line_Item_Details__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunity Line Items Details</relationshipLabel>
    <relationshipName>Opportunity_Line_Items_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opprtunity_Line_Item_Details__c/fields/Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Sub_Type__c</fullName>
    <label>Sub Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>SubType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opprtunity_Line_Item_Details__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Request_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Plan__c/Plan__c.object-meta.xml
<CustomObject>
    <label>Plan</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Plan__c/fields/Points__c.field-meta.xml
<CustomField>
    <fullName>Points__c</fullName>
    <label>Points</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Publication__c/Publication__c.object-meta.xml
<CustomObject>
    <label>Publication</label>
    <nameField>
        <label>Publication Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Publication__c/fields/Tag__c.field-meta.xml
<CustomField>
    <fullName>Tag__c</fullName>
    <label>Tag</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sub_Tags</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/City.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Spain</fullName>
    </customValue>
    <customValue>
        <fullName>France</fullName>
    </customValue>
    <masterLabel>City</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Request_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Travel Services</fullName>
    </customValue>
    <customValue>
        <fullName>Concierge Services</fullName>
    </customValue>
    <customValue>
        <fullName>Lifestyle Management Services</fullName>
    </customValue>
    <masterLabel>Request Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Sub_Tags.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Concerts</fullName>
    </customValue>
    <customValue>
        <fullName>Music Festivals</fullName>
    </customValue>
    <customValue>
        <fullName>Fashion Shows</fullName>
    </customValue>
    <customValue>
        <fullName>Opera</fullName>
    </customValue>
    <customValue>
        <fullName>Theatre</fullName>
    </customValue>
    <customValue>
        <fullName>Art &amp; Antique Fairs</fullName>
    </customValue>
    <customValue>
        <fullName>Water Sports</fullName>
    </customValue>
    <customValue>
        <fullName>Sports</fullName>
    </customValue>
    <customValue>
        <fullName>Sightseeing</fullName>
    </customValue>
    <customValue>
        <fullName>Wilderness &amp; Wildlife</fullName>
    </customValue>
    <customValue>
        <fullName>Desert Safari</fullName>
    </customValue>
    <customValue>
        <fullName>Cups &amp; Championships</fullName>
    </customValue>
    <customValue>
        <fullName>Meditation</fullName>
    </customValue>
    <customValue>
        <fullName>Relaxation</fullName>
    </customValue>
    <customValue>
        <fullName>Beauty</fullName>
    </customValue>
    <customValue>
        <fullName>Fitness</fullName>
    </customValue>
    <customValue>
        <fullName>Wellness Festivals</fullName>
    </customValue>
    <customValue>
        <fullName>Spirituality</fullName>
    </customValue>
    <customValue>
        <fullName>Rejuvenation</fullName>
    </customValue>
    <customValue>
        <fullName>Cuisine</fullName>
    </customValue>
    <customValue>
        <fullName>Culture</fullName>
    </customValue>
    <customValue>
        <fullName>History</fullName>
    </customValue>
    <customValue>
        <fullName>Social Happenings</fullName>
    </customValue>
    <customValue>
        <fullName>Seasonal Celebrations</fullName>
    </customValue>
    <customValue>
        <fullName>Family</fullName>
    </customValue>
    <customValue>
        <fullName>Business Travel</fullName>
    </customValue>
    <customValue>
        <fullName>Entrepreneurship</fullName>
    </customValue>
    <customValue>
        <fullName>Trade Shows &amp; Expos</fullName>
    </customValue>
    <customValue>
        <fullName>Incentive Trips &amp; Company Retreats</fullName>
    </customValue>
    <customValue>
        <fullName>Conferences &amp; Events</fullName>
    </customValue>
    <masterLabel>Sub-Tags</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Tier.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Lifestyle Private</fullName>
    </customValue>
    <customValue>
        <fullName>Dedicated Private</fullName>
    </customValue>
    <customValue>
        <fullName>Bespoke Private</fullName>
    </customValue>
    <customValue>
        <fullName>Classic Corporate</fullName>
    </customValue>
    <customValue>
        <fullName>Executive Corporate</fullName>
    </customValue>
    <customValue>
        <fullName>Gold</fullName>
        <isActive>false</isActive>
        <label>Gold</label>
    </customValue>
    <description>membership Tiers</description>
    <masterLabel>Tier</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Test/DataFactoryTest.cls
/**
 * @description       : 
 * @author            : Mohamed Tarek
 * @group             : 
 * @last modified on  : 02-15-2023
 * @last modified by  : Mohamed Tarek
**/
@isTest
public class DataFactoryTest {
    private static DataFactoryTest instance;


    private DataFactoryTest() {

    }

    public static DataFactoryTest getInstance(){
        if(instance == null){
            instance = new DataFactoryTest();
        }
        return instance;
    }
    
    public Account CreateAccount(String firstName, String lastName){
        Account account = new Account(
            Name = firstName + '  ' + lastName,
            Type= 'Prospect');
        insert account;
        return account;
    } 
    public Contact CreateContact(String firstName, String lastName, String password, String email, String accountId){
        Contact contact = new Contact( 
            FirstName=firstName,
            LastName=lastName,
            Password__c=password,
            UserName__c=email,
            AccountId=accountId);
        insert contact;
        return contact;
    } 

    public Membership__c CreateExternalMemberShip(Contact contact, Date expirationDate, String membershipID, String membershipProvider){
         Membership__c	membership = new Membership__c( 
            Contact__c=contact.Id,
            Expiration_Date__c=expirationDate,
            Name=membershipID,
            MemberShip_Provider__c=membershipProvider);
        insert membership;
        return membership;
    } 
    public City_Guide__c CreateCityGuide(String cityGuideName, String city, Integer duration, Decimal price){
        City_Guide__c	CityGuide = new City_Guide__c( 
           Name=cityGuideName,
           City__c=city,
           Duration__c=duration,
           Price__c=price);
       insert CityGuide;
       return CityGuide;
   } 
    public Contact_City_Guide__c CreateContactCityGuide(Contact contact, City_Guide__c cityGuide, Date startDate, Date endDate){
        Contact_City_Guide__c	contactCityGuide = new Contact_City_Guide__c( 
           Contact__c=contact.Id,
           City_Guide__c=cityGuide.Id,
           End_Date__c=endDate,
           Start_Date__c=startDate);
       insert contactCityGuide;
       return contactCityGuide;
   } 

   public Catalogue__c CreateCatalogue( String recordType ,String name, String logo, String city){
    Id recordTypeId = Schema.SObjectType.Catalogue__c.getRecordTypeInfosByName().get(recordType).getRecordTypeId();
    Catalogue__c catalogue = new Catalogue__c( 
       Name=name,
       Logo__c=logo,
       City__c=city,
       RecordTypeId=recordTypeId);
   insert catalogue;
   return catalogue;
} 
public Publication__c CreatePublication( String tag ,String name){
    Publication__c publication = new Publication__c( 
       Name=name,
       Tag__c=tag,
       Active__c = true);
   insert publication;
   return publication;
} 
public Plan__c CreatePlan(String planName, Integer points){
    Plan__c	plan = new Plan__c( 
       Name=planName,
       Points__c=points);
   insert plan;
   return plan;
} 
public Case CreateCase(String contactId	, String accountId){
    Id recordTypeId = Schema.SObjectType.Catalogue__c.getRecordTypeInfosByName().get('Reservation').getRecordTypeId();
    Case caseTest = new Case( 
       ContactId= contactId,
       AccountId=accountId,
       Origin='Web',
       Status='Paid',
       RecordTypeId=recordTypeId);
   insert caseTest;
   return caseTest;
} 
public Opprtunity_Line_Item_Details__c createOpprtunity_Line_Items_Details(String type,String subtype,DateTime arrival,DateTime departure){
    Opprtunity_Line_Item_Details__c opprtunityLineItemDetailsMock=new Opprtunity_Line_Item_Details__c();
    opprtunityLineItemDetailsMock.Type__c=type;
    opprtunityLineItemDetailsMock.Sub_Type__c=subType;
    opprtunityLineItemDetailsMock.Arival_Date__c=arrival;
    opprtunityLineItemDetailsMock.Departure_Date__c=departure;
    insert opprtunityLineItemDetailsMock;
    return opprtunityLineItemDetailsMock;
}
public Help_QA__c createHelp(String type,String category,String header,String body){
    Help_QA__c helpMock=new Help_QA__c();
    helpMock.Type__c=type;
    helpMock.Category__c=null;
    helpMock.Header__c=header;
    helpMock.Body__c=body;
    insert helpMock;
    return helpMock;
}

 
}