force-app/main/default/objects/Publication__c/Publication__c.object-meta.xml
<CustomObject>
    <label>Publication</label>
    <nameField>
        <label>Publication Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Publication__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>130768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Publication__c/fields/Discount_Amount__c.field-meta.xml
<CustomField>
    <fullName>Discount_Amount__c</fullName>
    <label>Discount Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Publication__c/fields/Discount_Type__c.field-meta.xml
<CustomField>
    <fullName>Discount_Type__c</fullName>
    <label>Discount Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Percentage</fullName>
            </value>
            <value>
                <fullName>Amount</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Publication__c/fields/Image__c.field-meta.xml
<CustomField>
    <fullName>Image__c</fullName>
    <label>Image</label>
    <length>130768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Publication__c/fields/Promo_code__c.field-meta.xml
<CustomField>
    <fullName>Promo_code__c</fullName>
    <label>Promo code</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Publication__c/fields/Show_on_External_App__c.field-meta.xml
<CustomField>
    <fullName>Show_on_External_App__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Show on External App</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Publication__c/fields/Tag__c.field-meta.xml
<CustomField>
    <fullName>Tag__c</fullName>
    <label>Tag</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sub_Tags</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Sub_Tags.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Concerts</fullName>
    </customValue>
    <customValue>
        <fullName>Music Festivals</fullName>
    </customValue>
    <customValue>
        <fullName>Fashion Shows</fullName>
    </customValue>
    <customValue>
        <fullName>Opera</fullName>
    </customValue>
    <customValue>
        <fullName>Theatre</fullName>
    </customValue>
    <customValue>
        <fullName>Art &amp; Antique Fairs</fullName>
    </customValue>
    <customValue>
        <fullName>Water Sports</fullName>
    </customValue>
    <customValue>
        <fullName>Sports</fullName>
    </customValue>
    <customValue>
        <fullName>Sightseeing</fullName>
    </customValue>
    <customValue>
        <fullName>Wilderness &amp; Wildlife</fullName>
    </customValue>
    <customValue>
        <fullName>Desert Safari</fullName>
    </customValue>
    <customValue>
        <fullName>Cups &amp; Championships</fullName>
    </customValue>
    <customValue>
        <fullName>Meditation</fullName>
    </customValue>
    <customValue>
        <fullName>Relaxation</fullName>
    </customValue>
    <customValue>
        <fullName>Beauty</fullName>
    </customValue>
    <customValue>
        <fullName>Fitness</fullName>
    </customValue>
    <customValue>
        <fullName>Wellness Festivals</fullName>
    </customValue>
    <customValue>
        <fullName>Spirituality</fullName>
    </customValue>
    <customValue>
        <fullName>Rejuvenation</fullName>
    </customValue>
    <customValue>
        <fullName>Cuisine</fullName>
    </customValue>
    <customValue>
        <fullName>Culture</fullName>
    </customValue>
    <customValue>
        <fullName>History</fullName>
    </customValue>
    <customValue>
        <fullName>Social Happenings</fullName>
    </customValue>
    <customValue>
        <fullName>Seasonal Celebrations</fullName>
    </customValue>
    <customValue>
        <fullName>Family</fullName>
    </customValue>
    <customValue>
        <fullName>Business Travel</fullName>
    </customValue>
    <customValue>
        <fullName>Entrepreneurship</fullName>
    </customValue>
    <customValue>
        <fullName>Trade Shows &amp; Expos</fullName>
    </customValue>
    <customValue>
        <fullName>Incentive Trips &amp; Company Retreats</fullName>
    </customValue>
    <customValue>
        <fullName>Conferences &amp; Events</fullName>
    </customValue>
    <masterLabel>Sub-Tags</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Repository/PublicationRepository.cls
public class PublicationRepository {

    private static PublicationRepository instance = null;
    private PublicationRepository(){}

    public static PublicationRepository getInstance() {
        if (instance == null) {
          instance = new PublicationRepository();
        }
        return instance;
      }

      public List<Publication__c> findAllPublications(Integer pageSize,Integer pageNumber){
        Integer offset = pageSize*(pageNumber-1);
        return [
          SELECT
            Name,
            Start_Date__c,
            End_Date__c,
            Discount_Amount__c,
            Discount_Type__c,
            Image__c,
            Promo_code__c,
            Tag__c,
            Location__c,
            Description__c,
            Catalogue__r.Id,
            Catalogue__r.RecordType.Name
          FROM Publication__c
          WHERE Active__c = true
          ORDER BY createddate 
          DESC LIMIT :pageSize OFFSET :offset];
      }
      public List<Publication__c> findPublicationsByRecordId( Id recordTypeId,Integer pageSize,Integer pageNumber){
        Integer offset = pageSize*(pageNumber-1);
        return [
          SELECT
            Name,
            Start_Date__c,
            End_Date__c,
            Discount_Amount__c,
            Discount_Type__c,
            Image__c,
            Promo_code__c,
            Tag__c,
            Location__c,
            Description__c,
            Catalogue__r.Id,
            Catalogue__r.RecordType.Name
          FROM Publication__c
          WHERE Active__c = true
          AND RecordTypeId =:recordTypeId
          ORDER BY createddate 
          DESC LIMIT :pageSize OFFSET :offset ];
      }

      public List<Publication__c> findPublicationsByRecordIdShowOnExternalApp( Id recordTypeId,Integer pageSize,Integer pageNumber){
        Integer offset = pageSize*(pageNumber-1);
        return [
          SELECT
            Name,
            Start_Date__c,
            End_Date__c,
            Discount_Amount__c,
            Discount_Type__c,
            Image__c,
            Promo_code__c,
            Tag__c,
            Location__c,
            Description__c,
            Catalogue__r.Id,
            Catalogue__r.RecordType.Name
          FROM Publication__c
          WHERE Active__c = true
          AND RecordTypeId =:recordTypeId 
          AND Show_on_External_App__c = true
          ORDER BY createddate 
          DESC LIMIT :pageSize OFFSET :offset];
      }
      public List<Publication__c> findAllPublicationsShowOnExternalApp(Integer pageSize,Integer pageNumber){
        Integer offset = pageSize*(pageNumber-1);
        return [
          SELECT
            Name,
            Start_Date__c,
            End_Date__c,
            Discount_Amount__c,
            Discount_Type__c,
            Image__c,
            Promo_code__c,
            Tag__c,
            Location__c,
            Description__c,
            Catalogue__r.Id,
            Catalogue__r.RecordType.Name
          FROM Publication__c
          WHERE Show_on_External_App__c = true
          AND Active__c = true
          ORDER BY createddate 
          DESC LIMIT :pageSize OFFSET :offset];
      }

      public List<Publication__c> findByTags(List<String> tagslist,Integer pageSize,Integer pageNumber){
        Integer offset = pageSize*(pageNumber-1);

        return [
          SELECT
            Name,
            Start_Date__c,
            End_Date__c,
            Discount_Amount__c,
            Discount_Type__c,
            Image__c,
            Tag__c,
            Location__c,
            Description__c,
            Catalogue__r.Id,
            Catalogue__r.RecordType.Name
          FROM Publication__c
          WHERE Tag__c = : tagslist
          AND Active__c = true
          ORDER BY createddate 
          DESC LIMIT :pageSize OFFSET :offset];
      }

      public List<Publication__c> findByTagsandRecordId(List<String> tagslist, Id recordTypeId,Integer pageSize,Integer pageNumber){
        Integer offset = pageSize*(pageNumber-1);
        return [
          SELECT
            Name,
            Start_Date__c,
            End_Date__c,
            Discount_Amount__c,
            Discount_Type__c,
            Image__c,
            Tag__c,
            Location__c,
            Description__c,
            Catalogue__r.Id,
            Catalogue__r.RecordType.Name
          FROM Publication__c
          WHERE Tag__c = : tagslist
          AND RecordTypeId =:recordTypeId 
          AND Active__c = true
          ORDER BY createddate 
          DESC LIMIT :pageSize OFFSET :offset];
      }

      public List<Publication__c> findExternalappByTags(List<String> tagslist,Integer pageSize,Integer pageNumber){
        Integer offset = pageSize*(pageNumber-1);
        return [
          SELECT
            Name,
            Start_Date__c,
            End_Date__c,
            Discount_Amount__c,
            Discount_Type__c,
            Image__c,
            Tag__c,
            Location__c,
            Description__c,
            Catalogue__r.Id,
            Catalogue__r.RecordType.Name
          FROM Publication__c
          WHERE Tag__c = :tagslist
          AND Show_on_External_App__c = true
          AND Active__c = true
          ORDER BY createddate 
          DESC LIMIT :pageSize OFFSET :offset];
      }
      public List<Publication__c> findExternalappByTagsandRecordId(List<String> tagslist,Id recordTypeId,Integer pageSize,Integer pageNumber){
        Integer offset = pageSize*(pageNumber-1);
        return [
          SELECT
            Name,
            Start_Date__c,
            End_Date__c,
            Discount_Amount__c,
            Discount_Type__c,
            Image__c,
            Tag__c,
            Location__c,
            Description__c,
            Catalogue__r.Id,
            Catalogue__r.RecordType.Name
          FROM Publication__c
          WHERE Tag__c = :tagslist
          AND Show_on_External_App__c = true
          AND RecordTypeId =:recordTypeId 
          AND Active__c = true
          ORDER BY createddate 
          DESC LIMIT :pageSize OFFSET :offset];
      }
      public Publication__c findPublicationbyPage(String page){
       
        return [
          SELECT
            Name,
            Start_Date__c,
            End_Date__c,
            Discount_Amount__c,
            Discount_Type__c,
            Image__c,
            Tag__c,
            Location__c,
            Description__c,
            Catalogue__r.Id,
            Catalogue__r.RecordType.Name
          FROM Publication__c
          WHERE Page__c	 = :page
          AND Active__c = true];
      }
      
}