force-app/main/default/objects/QuoteLineItem/fields/Breakfast__c.field-meta.xml
<CustomField>
    <fullName>Breakfast__c</fullName>
    <label>Breakfast</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Commission__c.field-meta.xml
<CustomField>
    <fullName>Commission__c</fullName>
    <formula>(VAT__c * (Total_rate__c - Breakfast__c ))*(Line_Item_Detail__r.Opportunity_Line_Item_Details__r.Supplier__r.Supplier_Comission__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Commission</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Extra_Charges_Amount__c.field-meta.xml
<CustomField>
    <fullName>Extra_Charges_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Extra Charges Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Line_Item_Detail__c.field-meta.xml
<CustomField>
    <fullName>Line_Item_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Line Item Detail</label>
    <referenceTo>Quote_Line_Item_Detail__c</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>Quote_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Markup__c.field-meta.xml
<CustomField>
    <fullName>Markup__c</fullName>
    <label>Markup %</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Markup_Amount__c.field-meta.xml
<CustomField>
    <fullName>Markup_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Markup Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Total_rate__c.field-meta.xml
<CustomField>
    <fullName>Total_rate__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/VAT__c.field-meta.xml
<CustomField>
    <fullName>VAT__c</fullName>
    <label>VAT %</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/Repository/QuoteLineItemRepository.cls
public class QuoteLineItemRepository {
    private static QuoteLineItemRepository instance = null;
    private QuoteLineItemRepository(){}

    public static QuoteLineItemRepository getInstance() {
        if (instance == null) {
          instance = new QuoteLineItemRepository();
        }
        return instance;
      }
      public List<QuoteLineItem> findAllQuoteLineItems(){
        return [
            SELECT
            Breakfast__c,
            Commission__c,
            Discount,
            Extra_Charges_Amount__c,
            Description,
            Line_Item_Detail__c,
            LineNumber,
            ListPrice,
            Markup__c,
            Markup_Amount__c,
            Product2Id,
            Quantity,
            QuoteId,
            Quote.Sequence_Number__c,
            UnitPrice,
            Subtotal,
            TotalPrice,
            Total_rate__c,
            VAT__c
            FROM QuoteLineItem
        ];
      }

      public List<QuoteLineItem> findQuoteLineItemByQuoteId(String quoteId){
        return [
            SELECT
            Breakfast__c,
            Commission__c,
            Discount,
            Extra_Charges_Amount__c,
            Description,
            Line_Item_Detail__c,
            LineNumber,
            ListPrice,
            Markup__c,
            Markup_Amount__c,
            Product2Id,
            Quantity,
            QuoteId,
            Quote.Sequence_Number__c,
            UnitPrice,
            Subtotal,
            TotalPrice,
            Total_rate__c,
            VAT__c
            FROM QuoteLineItem
            WHERE QuoteId = :quoteId
        ];
      }

      public List<QuoteLineItem> findQuoteLineItemByQuoteLineItemDetailsId(List<Id> quoteLineItemDetails){
        return [
            SELECT
            Breakfast__c,
            Commission__c,
            Discount,
            Extra_Charges_Amount__c,
            Description,
            Line_Item_Detail__c,
            LineNumber,
            ListPrice,
            Markup__c,
            Markup_Amount__c,
            Product2.Name,
            Quantity,
            QuoteId,
            Quote.Sequence_Number__c,
            Quote.Status,
            UnitPrice,
            Subtotal,
            TotalPrice,
            Total_rate__c,
            VAT__c
            FROM QuoteLineItem
            WHERE Line_Item_Detail__c = :quoteLineItemDetails
        ];
      }
}