force-app/main/default/objects/Membership__c/Membership__c.object-meta.xml
<CustomObject>
    <label>Membership</label>
    <nameField>
        <label>Membership ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Memberships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Membership__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Memberships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Membership__c/fields/MemberShip_Provider__c.field-meta.xml
<CustomField>
    <fullName>MemberShip_Provider__c</fullName>
    <label>Membership Provider</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Repository/ExternalMembershipsRepository.cls
public class ExternalMembershipsRepository {
    private static ExternalMembershipsRepository instance = null;
    private ExternalMembershipsRepository() {}

    public static ExternalMembershipsRepository getInstance() {
        if (instance == null) {
          instance = new ExternalMembershipsRepository();
        }
        return instance;
      }

    public List<MemberShip__c> findByContact(Contact contact){

        return [
          SELECT
          Name,
          MemberShip_Provider__c,
          Expiration_Date__c,
          Id		
          FROM MemberShip__c
          WHERE Contact__c = :contact.Id
          ];
    }

    public List<MemberShip__c>  findById(List<String> id){

        return [
          SELECT
          Name,
          MemberShip_Provider__c,
          Id,
          Expiration_Date__c
          FROM MemberShip__c
          WHERE Id = : id
          ];
    }

}