force-app/main/default/objects/Membership__c/Membership__c.object-meta.xml
<CustomObject>
    <label>Membership</label>
    <nameField>
        <label>Membership ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Memberships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Membership__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Memberships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Membership__c/fields/MemberShip_Provider__c.field-meta.xml
<CustomField>
    <fullName>MemberShip_Provider__c</fullName>
    <label>Membership Provider</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Membership__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Password</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Mapper/ExternalMembershipsMapper.cls
global class ExternalMembershipsMapper {

    String memberShipId;
    String memberShipProvider;
    String  expirationDate;
    String id;
    public ExternalMembershipsMapper() {

    }
    public ExternalMembershipsMapper MembershipMapperToObject(MemberShip__c membershipObject){

        ExternalMembershipsMapper externalMembershipsMapper = new ExternalMembershipsMapper();
        externalMembershipsMapper.memberShipId = membershipObject.Name;
        externalMembershipsMapper.memberShipProvider = membershipObject.MemberShip_Provider__c;
        externalMembershipsMapper.expirationDate = (membershipObject.Expiration_Date__c.format()).replace('-','/');
        externalMembershipsMapper.id = membershipObject.Id;
        return externalMembershipsMapper;
    }

    public List<ExternalMembershipsMapper>  MembershipListToObject(List<MemberShip__c> membershipObjectList){
        List<ExternalMembershipsMapper> externalMembershipsMapper = new List<ExternalMembershipsMapper>();
       
        for( MemberShip__c p : membershipObjectList ){

            externalMembershipsMapper.add(MembershipMapperToObject(p));
        }

        return externalMembershipsMapper;

    }

    public List<MemberShip__c> MembershipAPIListToObject(String contactId , List<Object> membershipMapper){
        List<MemberShip__c> externalMemberships = new List<MemberShip__c>();
        Integer counter = 0;
        while (counter < membershipMapper.size()){
            MemberShip__c membership = new MemberShip__c();
            Map<String, Object> membershipmap =(Map<String, Object>)membershipMapper.get(counter);
           
           if((String)membershipmap.get('id')!=null){
            membership.Id = (String)membershipmap.get('id');
            membership.Expiration_Date__c =Date.parse((String)membershipmap.get('expirationDate'));
            membership.MemberShip_Provider__c =(String) membershipmap.get('memberShipProvider');
            membership.Name = (String)membershipmap.get('memberShipId');
            membership.Password__c = (String)membershipmap.get('Password');
           }else{
            membership.Expiration_Date__c =Date.parse((String)membershipmap.get('expirationDate'));
            membership.MemberShip_Provider__c =(String) membershipmap.get('memberShipProvider');
            membership.Name = (String)membershipmap.get('memberShipId');
            membership.Password__c = (String)membershipmap.get('Password');
            membership.Contact__c= contactId;}
            externalMemberships.add(membership);
            counter += 1;
        }

        return externalMemberships;
    }
}