force-app/main/default/objects/Opportunity/fields/Request__c.field-meta.xml
<CustomField>
    <fullName>Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Request</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Packages</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opprtunity_Line_Item_Details__c/Opprtunity_Line_Item_Details__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <label>Opprtunity Line Item Details Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote_Line_Item_Detail__c/Quote_Line_Item_Detail__c.object-meta.xml
<CustomObject>
    <label>Quote Line Item Detail</label>
    <nameField>
        <label>Quote Line Item Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Line Items Detail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote_Line_Item_Detail__c/fields/Airline1__c.field-meta.xml
<CustomField>
    <fullName>Airline1__c</fullName>
    <label>Airline</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item_Detail__c/fields/Airline3__c.field-meta.xml
<CustomField>
    <fullName>Airline3__c</fullName>
    <label>Airline</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item_Detail__c/fields/Airline__c.field-meta.xml
<CustomField>
    <fullName>Airline__c</fullName>
    <label>Airline</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item_Detail__c/fields/Airport__c.field-meta.xml
<CustomField>
    <fullName>Airport__c</fullName>
    <label>Airport</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item_Detail__c/fields/Arival_Date2__c.field-meta.xml
<CustomField>
    <fullName>Arival_Date2__c</fullName>
    <label>Arival Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item_Detail__c/fields/Arival_Date3__c.field-meta.xml
<CustomField>
    <fullName>Arival_Date3__c</fullName>
    <label>Arival Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item_Detail__c/fields/Arival_Date4__c.field-meta.xml
<CustomField>
    <fullName>Arival_Date4__c</fullName>
    <label>Arival Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item_Detail__c/fields/Arival_Date__c.field-meta.xml
<CustomField>
    <fullName>Arival_Date__c</fullName>
    <label>Arival Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item_Detail__c/fields/Bed_size__c.field-meta.xml
<CustomField>
    <fullName>Bed_size__c</fullName>
    <label>Bed size</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>King</fullName>
            </value>
            <value>
                <fullName>Double</fullName>
            </value>
            <value>
                <fullName>Single</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote_Line_Item_Detail__c/fields/Bookings__c.field-meta.xml
<CustomField>
    <fullName>Bookings__c</fullName>
    <label>Number of Bookings</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item_Detail__c/fields/Class1__c.field-meta.xml
<CustomField>
    <fullName>Class1__c</fullName>
    <label>Class</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Class</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote_Line_Item_Detail__c/fields/Class2__c.field-meta.xml
<CustomField>
    <fullName>Class2__c</fullName>
    <label>Class</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Class</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote_Line_Item_Detail__c/fields/Class3__c.field-meta.xml
<CustomField>
    <fullName>Class3__c</fullName>
    <label>Class</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Class</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote_Line_Item_Detail__c/fields/Class4__c.field-meta.xml
<CustomField>
    <fullName>Class4__c</fullName>
    <label>Class</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Class</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote_Line_Item_Detail__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>Class</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Class</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote_Line_Item_Detail__c/fields/Departure1__c.field-meta.xml
<CustomField>
    <fullName>Departure1__c</fullName>
    <label>Departure</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item_Detail__c/fields/Departure2__c.field-meta.xml
<CustomField>
    <fullName>Departure2__c</fullName>
    <label>Departure</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item_Detail__c/fields/Departure3__c.field-meta.xml
<CustomField>
    <fullName>Departure3__c</fullName>
    <label>Departure</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item_Detail__c/fields/Departure4__c.field-meta.xml
<CustomField>
    <fullName>Departure4__c</fullName>
    <label>Departure</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item_Detail__c/fields/Departure__c.field-meta.xml
<CustomField>
    <fullName>Departure__c</fullName>
    <label>Departure</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item_Detail__c/fields/Departure_Date1__c.field-meta.xml
<CustomField>
    <fullName>Departure_Date1__c</fullName>
    <label>Departure Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item_Detail__c/fields/Departure_Date2__c.field-meta.xml
<CustomField>
    <fullName>Departure_Date2__c</fullName>
    <label>Departure Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item_Detail__c/fields/Departure_Date3__c.field-meta.xml
<CustomField>
    <fullName>Departure_Date3__c</fullName>
    <label>Departure Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item_Detail__c/fields/Departure_Date4__c.field-meta.xml
<CustomField>
    <fullName>Departure_Date4__c</fullName>
    <label>Departure Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item_Detail__c/fields/Departure_Date__c.field-meta.xml
<CustomField>
    <fullName>Departure_Date__c</fullName>
    <label>Departure Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item_Detail__c/fields/Destination1__c.field-meta.xml
<CustomField>
    <fullName>Destination1__c</fullName>
    <label>Destination</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item_Detail__c/fields/Destination2__c.field-meta.xml
<CustomField>
    <fullName>Destination2__c</fullName>
    <label>Destination</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item_Detail__c/fields/Destination3__c.field-meta.xml
<CustomField>
    <fullName>Destination3__c</fullName>
    <label>Destination</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item_Detail__c/fields/Destination4__c.field-meta.xml
<CustomField>
    <fullName>Destination4__c</fullName>
    <label>Destination</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item_Detail__c/fields/Destination__c.field-meta.xml
<CustomField>
    <fullName>Destination__c</fullName>
    <label>Destination</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item_Detail__c/fields/Hotel__c.field-meta.xml
<CustomField>
    <fullName>Hotel__c</fullName>
    <label>Hotel</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item_Detail__c/fields/Meal_Plan__c.field-meta.xml
<CustomField>
    <fullName>Meal_Plan__c</fullName>
    <label>Meal Plan</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Meal_Plan</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote_Line_Item_Detail__c/fields/Opportunity_Line_Item_Details__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Line_Item_Details__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Line Item Details</label>
    <referenceTo>Opprtunity_Line_Item_Details__c</referenceTo>
    <relationshipLabel>Quote Line Items Detail</relationshipLabel>
    <relationshipName>Quote_Line_Items_Detail</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item_Detail__c/fields/Sales_Price__c.field-meta.xml
<CustomField>
    <fullName>Sales_Price__c</fullName>
    <label>Sales Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item_Detail__c/fields/SubType__c.field-meta.xml
<CustomField>
    <fullName>SubType__c</fullName>
    <formula>Text(Opportunity_Line_Item_Details__r.Sub_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SubType</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item_Detail__c/fields/Trip_type__c.field-meta.xml
<CustomField>
    <fullName>Trip_type__c</fullName>
    <formula>TEXT(Opportunity_Line_Item_Details__r.Trip_type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Trip type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Line_Item_Detail__c.field-meta.xml
<CustomField>
    <fullName>Line_Item_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Line Item Detail</label>
    <referenceTo>Quote_Line_Item_Detail__c</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>Quote_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Class.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Economy</fullName>
    </customValue>
    <customValue>
        <fullName>First</fullName>
    </customValue>
    <customValue>
        <fullName>Business</fullName>
    </customValue>
    <masterLabel>Class</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Meal_Plan.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Breakfast</fullName>
    </customValue>
    <customValue>
        <fullName>Half board</fullName>
    </customValue>
    <customValue>
        <fullName>Full board</fullName>
    </customValue>
    <masterLabel>Meal Plan</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/VisualForce/Extensions/PricingQuotationExtension.cls
/**
 * @description       :
 * @author            : Ahmed Abdelraouf
 * @group             :
 * @last modified on  : 01-28-2023
 * @last modified by  : Ahmed Abdelraouf
 **/
public class PricingQuotationExtension {
  public Boolean readValue { get; set; }

  public static final string FLIGHT_MANAGEMENT = 'Flight Management';
  public static final string ACCOMMODATION_MANAGEMENT = 'Accommodation Management';

  public static final string FLIGHT_MANAGEMENT_TRIP_TYPE_ONE_WAY = 'One-way';
  public static final string FLIGHT_MANAGEMENT_TRIP_TYPE_ROUNDTRIP = 'RoundTrip';
  public static final string FLIGHT_MANAGEMENT_TRIP_TYPE_MULTI_CITY = 'Multi-city';

  public Opportunity opportunity { get; set; }
  public PricingQuotationExtension(ApexPages.StandardController controller) {
    this.opportunity = (Opportunity) controller.getRecord();
    // this.opportunity = getOpportunityDetails('0067X00000DisRAQAZ');
    this.opportunity = getOpportunityDetails(this.opportunity.Id);
  }

  public Contact getContactInfo() {
    return [
        SELECT
          Id,
          Name,
          Phone,
          Account.Name,
          MailingStreet,
          MailingCity,
          MailingCountry
        FROM Contact
        WHERE Id = :this.opportunity.Request__r.ContactId
      ]
      .get(0);
  }

  // public Quote getQuote() {
  //   return [
  //       SELECT Id, Name, TotalPrice, OpportunityId
  //       FROM Quote
  //       WHERE OpportunityId = :this.opportunity.Id
  //     ]
  //     .get(0);
  // }

  public List<QuoteLineItem> getQuoteLineItemsAccomedation() {
    return [
      SELECT
        Id,
        QuoteId,
        Line_Item_Detail__c,
        Product2Id,
        Product2.Name,
        TotalPrice,
        Line_Item_Detail__r.Hotel__c,
        Line_Item_Detail__r.Bookings__c,
        Line_Item_Detail__r.Sales_Price__c,
        Line_Item_Detail__r.Room__c,
        Line_Item_Detail__r.Bed_size__c,
        Line_Item_Detail__r.Meal_Plan__c,
        Line_Item_Detail__r.Class__c,
        Line_Item_Detail__r.Class1__c,
        Line_Item_Detail__r.Class2__c,
        Line_Item_Detail__r.Class3__c,
        Line_Item_Detail__r.Class4__c,
        Line_Item_Detail__r.Arival_Date__c,
        Line_Item_Detail__r.Arival_Date1__c,
        Line_Item_Detail__r.Arival_Date2__c,
        Line_Item_Detail__r.Arival_Date3__c,
        Line_Item_Detail__r.Arival_Date4__c,
        Line_Item_Detail__r.Departure_Date__c,
        Line_Item_Detail__r.Departure_Date1__c,
        Line_Item_Detail__r.Departure_Date2__c,
        Line_Item_Detail__r.Departure_Date3__c,
        Line_Item_Detail__r.Departure_Date4__c,
        Line_Item_Detail__r.Destination__c,
        Line_Item_Detail__r.Destination1__c,
        Line_Item_Detail__r.Destination2__c,
        Line_Item_Detail__r.Destination3__c,
        Line_Item_Detail__r.Destination4__c,
        Line_Item_Detail__r.Departure__c,
        Line_Item_Detail__r.Departure1__c,
        Line_Item_Detail__r.Departure2__c,
        Line_Item_Detail__r.Departure3__c,
        Line_Item_Detail__r.Departure4__c,
        Line_Item_Detail__r.Airline__c,
        Line_Item_Detail__r.Airport__c,
        Line_Item_Detail__r.Airline1__c,
        Line_Item_Detail__r.Airline2__c,
        Line_Item_Detail__r.Airline3__c,
        Line_Item_Detail__r.Airline4__c,
        Line_Item_Detail__r.Trip_type__c,
        Line_Item_Detail__r.SubType__c,
        Line_Item_Detail__r.Description__c,
        Line_Item_Detail__r.Opportunity_Line_Item_Details__r.Category__c
      FROM QuoteLineItem
      WHERE
        Quote.OpportunityId = :this.opportunity.Id
        AND Product2.Name = :ACCOMMODATION_MANAGEMENT
    ];
  }

  public List<QuoteLineItem> getQuoteLineItemsFlightOneWay() {
    return [
      SELECT
        Id,
        QuoteId,
        Line_Item_Detail__c,
        Product2Id,
        Product2.Name,
        TotalPrice,
        Line_Item_Detail__r.Hotel__c,
        Line_Item_Detail__r.Bookings__c,
        Line_Item_Detail__r.Sales_Price__c,
        Line_Item_Detail__r.Room__c,
        Line_Item_Detail__r.Bed_size__c,
        Line_Item_Detail__r.Meal_Plan__c,
        Line_Item_Detail__r.Class__c,
        Line_Item_Detail__r.Class1__c,
        Line_Item_Detail__r.Class2__c,
        Line_Item_Detail__r.Class3__c,
        Line_Item_Detail__r.Class4__c,
        Line_Item_Detail__r.Arival_Date__c,
        Line_Item_Detail__r.Arival_Date1__c,
        Line_Item_Detail__r.Arival_Date2__c,
        Line_Item_Detail__r.Arival_Date3__c,
        Line_Item_Detail__r.Arival_Date4__c,
        Line_Item_Detail__r.Departure_Date__c,
        Line_Item_Detail__r.Departure_Date1__c,
        Line_Item_Detail__r.Departure_Date2__c,
        Line_Item_Detail__r.Departure_Date3__c,
        Line_Item_Detail__r.Departure_Date4__c,
        Line_Item_Detail__r.Destination__c,
        Line_Item_Detail__r.Destination1__c,
        Line_Item_Detail__r.Destination2__c,
        Line_Item_Detail__r.Destination3__c,
        Line_Item_Detail__r.Destination4__c,
        Line_Item_Detail__r.Departure__c,
        Line_Item_Detail__r.Departure1__c,
        Line_Item_Detail__r.Departure2__c,
        Line_Item_Detail__r.Departure3__c,
        Line_Item_Detail__r.Departure4__c,
        Line_Item_Detail__r.Airline__c,
        Line_Item_Detail__r.Airport__c,
        Line_Item_Detail__r.Airline1__c,
        Line_Item_Detail__r.Airline2__c,
        Line_Item_Detail__r.Airline3__c,
        Line_Item_Detail__r.Airline4__c,
        Line_Item_Detail__r.Trip_type__c,
        Line_Item_Detail__r.SubType__c,
        Line_Item_Detail__r.Description__c
      FROM QuoteLineItem
      WHERE
        Quote.OpportunityId = :this.opportunity.Id
        AND Product2.Name = :FLIGHT_MANAGEMENT
        AND Line_Item_Detail__r.Trip_type__c = :FLIGHT_MANAGEMENT_TRIP_TYPE_ONE_WAY
    ];
  }
  public List<QuoteLineItem> getQuoteLineItemsFlightRoundTrip() {
    return [
      SELECT
        Id,
        QuoteId,
        Line_Item_Detail__c,
        Product2Id,
        Product2.Name,
        TotalPrice,
        Line_Item_Detail__r.Hotel__c,
        Line_Item_Detail__r.Bookings__c,
        Line_Item_Detail__r.Sales_Price__c,
        Line_Item_Detail__r.Room__c,
        Line_Item_Detail__r.Bed_size__c,
        Line_Item_Detail__r.Meal_Plan__c,
        Line_Item_Detail__r.Class__c,
        Line_Item_Detail__r.Class1__c,
        Line_Item_Detail__r.Class2__c,
        Line_Item_Detail__r.Class3__c,
        Line_Item_Detail__r.Class4__c,
        Line_Item_Detail__r.Arival_Date__c,
        Line_Item_Detail__r.Arival_Date1__c,
        Line_Item_Detail__r.Arival_Date2__c,
        Line_Item_Detail__r.Arival_Date3__c,
        Line_Item_Detail__r.Arival_Date4__c,
        Line_Item_Detail__r.Departure_Date__c,
        Line_Item_Detail__r.Departure_Date1__c,
        Line_Item_Detail__r.Departure_Date2__c,
        Line_Item_Detail__r.Departure_Date3__c,
        Line_Item_Detail__r.Departure_Date4__c,
        Line_Item_Detail__r.Destination__c,
        Line_Item_Detail__r.Destination1__c,
        Line_Item_Detail__r.Destination2__c,
        Line_Item_Detail__r.Destination3__c,
        Line_Item_Detail__r.Destination4__c,
        Line_Item_Detail__r.Departure__c,
        Line_Item_Detail__r.Departure1__c,
        Line_Item_Detail__r.Departure2__c,
        Line_Item_Detail__r.Departure3__c,
        Line_Item_Detail__r.Departure4__c,
        Line_Item_Detail__r.Airline__c,
        Line_Item_Detail__r.Airport__c,
        Line_Item_Detail__r.Airline1__c,
        Line_Item_Detail__r.Airline2__c,
        Line_Item_Detail__r.Airline3__c,
        Line_Item_Detail__r.Airline4__c,
        Line_Item_Detail__r.Trip_type__c,
        Line_Item_Detail__r.SubType__c,
        Line_Item_Detail__r.Description__c
      FROM QuoteLineItem
      WHERE
        Quote.OpportunityId = :this.opportunity.Id
        AND Product2.Name = :FLIGHT_MANAGEMENT
        AND Line_Item_Detail__r.Trip_type__c = :FLIGHT_MANAGEMENT_TRIP_TYPE_ROUNDTRIP
    ];
  }

  public List<QuoteLineItem> getQuoteLineItemsFlightMultiCity() {
    return [
      SELECT
        Id,
        QuoteId,
        Line_Item_Detail__c,
        Product2Id,
        Product2.Name,
        TotalPrice,
        Line_Item_Detail__r.Hotel__c,
        Line_Item_Detail__r.Bookings__c,
        Line_Item_Detail__r.Sales_Price__c,
        Line_Item_Detail__r.Room__c,
        Line_Item_Detail__r.Bed_size__c,
        Line_Item_Detail__r.Meal_Plan__c,
        Line_Item_Detail__r.Class__c,
        Line_Item_Detail__r.Class1__c,
        Line_Item_Detail__r.Class2__c,
        Line_Item_Detail__r.Class3__c,
        Line_Item_Detail__r.Class4__c,
        Line_Item_Detail__r.Arival_Date__c,
        Line_Item_Detail__r.Arival_Date1__c,
        Line_Item_Detail__r.Arival_Date2__c,
        Line_Item_Detail__r.Arival_Date3__c,
        Line_Item_Detail__r.Arival_Date4__c,
        Line_Item_Detail__r.Departure_Date__c,
        Line_Item_Detail__r.Departure_Date1__c,
        Line_Item_Detail__r.Departure_Date2__c,
        Line_Item_Detail__r.Departure_Date3__c,
        Line_Item_Detail__r.Departure_Date4__c,
        Line_Item_Detail__r.Destination__c,
        Line_Item_Detail__r.Destination1__c,
        Line_Item_Detail__r.Destination2__c,
        Line_Item_Detail__r.Destination3__c,
        Line_Item_Detail__r.Destination4__c,
        Line_Item_Detail__r.Departure__c,
        Line_Item_Detail__r.Departure1__c,
        Line_Item_Detail__r.Departure2__c,
        Line_Item_Detail__r.Departure3__c,
        Line_Item_Detail__r.Departure4__c,
        Line_Item_Detail__r.Airline__c,
        Line_Item_Detail__r.Airport__c,
        Line_Item_Detail__r.Airline1__c,
        Line_Item_Detail__r.Airline2__c,
        Line_Item_Detail__r.Airline3__c,
        Line_Item_Detail__r.Airline4__c,
        Line_Item_Detail__r.Trip_type__c,
        Line_Item_Detail__r.SubType__c,
        Line_Item_Detail__r.Description__c
      FROM QuoteLineItem
      WHERE
        Quote.OpportunityId = :this.opportunity.Id
        AND Product2.Name = :FLIGHT_MANAGEMENT
        AND Line_Item_Detail__r.Trip_type__c = :FLIGHT_MANAGEMENT_TRIP_TYPE_MULTI_CITY
    ];
  }

  public List<QuoteLineItem> getQuoteLineItemsOtherProducts() {
    return [
      SELECT
        Id,
        QuoteId,
        Line_Item_Detail__c,
        Product2Id,
        Product2.Name,
        TotalPrice,
        Line_Item_Detail__r.Hotel__c,
        Line_Item_Detail__r.Bookings__c,
        Line_Item_Detail__r.Sales_Price__c,
        Line_Item_Detail__r.Room__c,
        Line_Item_Detail__r.Bed_size__c,
        Line_Item_Detail__r.Meal_Plan__c,
        Line_Item_Detail__r.Class__c,
        Line_Item_Detail__r.Class1__c,
        Line_Item_Detail__r.Class2__c,
        Line_Item_Detail__r.Class3__c,
        Line_Item_Detail__r.Class4__c,
        Line_Item_Detail__r.Arival_Date__c,
        Line_Item_Detail__r.Arival_Date1__c,
        Line_Item_Detail__r.Arival_Date2__c,
        Line_Item_Detail__r.Arival_Date3__c,
        Line_Item_Detail__r.Arival_Date4__c,
        Line_Item_Detail__r.Departure_Date__c,
        Line_Item_Detail__r.Departure_Date1__c,
        Line_Item_Detail__r.Departure_Date2__c,
        Line_Item_Detail__r.Departure_Date3__c,
        Line_Item_Detail__r.Departure_Date4__c,
        Line_Item_Detail__r.Destination__c,
        Line_Item_Detail__r.Destination1__c,
        Line_Item_Detail__r.Destination2__c,
        Line_Item_Detail__r.Destination3__c,
        Line_Item_Detail__r.Destination4__c,
        Line_Item_Detail__r.Departure__c,
        Line_Item_Detail__r.Departure1__c,
        Line_Item_Detail__r.Departure2__c,
        Line_Item_Detail__r.Departure3__c,
        Line_Item_Detail__r.Departure4__c,
        Line_Item_Detail__r.Airline__c,
        Line_Item_Detail__r.Airport__c,
        Line_Item_Detail__r.Airline1__c,
        Line_Item_Detail__r.Airline2__c,
        Line_Item_Detail__r.Airline3__c,
        Line_Item_Detail__r.Airline4__c,
        Line_Item_Detail__r.Trip_type__c,
        Line_Item_Detail__r.SubType__c,
        Line_Item_Detail__r.Description__c
      FROM QuoteLineItem
      WHERE
        Quote.OpportunityId = :this.opportunity.Id
        AND Product2.Name != :ACCOMMODATION_MANAGEMENT
        AND Product2.Name != :FLIGHT_MANAGEMENT
    ];
  }

  public Integer getQuoteLineItemsAccomedationSize() {
    Integer count = 0;
    for (AggregateResult groupedResult : [
      SELECT COUNT(Id)
      FROM QuoteLineItem
      WHERE
        Quote.OpportunityId = :this.opportunity.Id
        AND Product2.Name = :ACCOMMODATION_MANAGEMENT
    ]) {
      count = (Integer) groupedResult.get('expr0');
    }
    return count;
  }

  public Integer getQuoteLineItemsFlightOneWaySize() {
    Integer count = 0;
    for (AggregateResult groupedResult : [
      SELECT COUNT(Id)
      FROM QuoteLineItem
      WHERE
        Quote.OpportunityId = :this.opportunity.Id
        AND Product2.Name = :FLIGHT_MANAGEMENT
        AND Line_Item_Detail__r.Trip_type__c = :FLIGHT_MANAGEMENT_TRIP_TYPE_ONE_WAY
    ]) {
      count = (Integer) groupedResult.get('expr0');
    }
    return count;
  }

  public Integer getQuoteLineItemsFlightRoundTripSize() {
    Integer count = 0;
    for (AggregateResult groupedResult : [
      SELECT COUNT(Id)
      FROM QuoteLineItem
      WHERE
        Quote.OpportunityId = :this.opportunity.Id
        AND Product2.Name = :FLIGHT_MANAGEMENT
        AND Line_Item_Detail__r.Trip_type__c = :FLIGHT_MANAGEMENT_TRIP_TYPE_ROUNDTRIP
    ]) {
      count = (Integer) groupedResult.get('expr0');
    }
    return count;
  }

  public Integer getQuoteLineItemsFlightMultiCitySize() {
    Integer count = 0;
    for (AggregateResult groupedResult : [
      SELECT COUNT(Id)
      FROM QuoteLineItem
      WHERE
        Quote.OpportunityId = :this.opportunity.Id
        AND Product2.Name = :FLIGHT_MANAGEMENT
        AND Line_Item_Detail__r.Trip_type__c = :FLIGHT_MANAGEMENT_TRIP_TYPE_MULTI_CITY
    ]) {
      count = (Integer) groupedResult.get('expr0');
    }
    return count;
  }

  public Integer getQuoteLineItemsOtherProductsSize() {
    Integer count = 0;
    for (AggregateResult groupedResult : [
      SELECT COUNT(Id)
      FROM QuoteLineItem
      WHERE
        Quote.OpportunityId = :this.opportunity.Id
        AND Product2.Name != :ACCOMMODATION_MANAGEMENT
        AND Product2.Name != :FLIGHT_MANAGEMENT
    ]) {
      count = (Integer) groupedResult.get('expr0');
    }
    return count;
  }

  public Opportunity getOpportunityDetails(Id opportunityId) {
    return [
        SELECT Id, Request__c, Request__r.ContactId
        FROM Opportunity
        WHERE Id = :opportunityId
      ]
      .get(0);
  }
}