force-app/main/default/objects/Plan__c/Plan__c.object-meta.xml
<CustomObject>
    <label>Plan</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Plan__c/fields/Benefits__c.field-meta.xml
<CustomField>
    <fullName>Benefits__c</fullName>
    <label>Benefits</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Plan__c/fields/Points__c.field-meta.xml
<CustomField>
    <fullName>Points__c</fullName>
    <label>Points</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Repository/PlansRepository.cls
public class PlansRepository {
    private static PlansRepository instance = null;
    public PlansRepository() {

    }

    public static PlansRepository getInstance() {
        if (instance == null) {
          instance = new PlansRepository();
        }
        return instance;
      }

        public List<Plan__c> FindAllPlans() {
            return [
                SELECT
                Name,
                Points__c,
                Price__c,
                Benefits__c,
                Logo__c	
                FROM Plan__c
                
              ];
        }
        public Plan__c FindPlansById(String id) {
          
          return [
            SELECT
            Name,
            Points__c,
            Price__c,
            Benefits__c,
            Logo__c	
            FROM Plan__c
            WHERE Id = :id];

        }

        public Plan__c FindPlansByName(String name) {
          
          return [
            SELECT
            Name,
            Id,
            Points__c,
            Price__c,
            Benefits__c,
            Logo__c	
            FROM Plan__c
            WHERE Name = :name];

        }

}