force-app/main/default/objects/Plan__c/Plan__c.object-meta.xml
<CustomObject>
    <label>Plan</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Plan__c/fields/Benefits__c.field-meta.xml
<CustomField>
    <fullName>Benefits__c</fullName>
    <label>Benefits</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Plan__c/fields/Points__c.field-meta.xml
<CustomField>
    <fullName>Points__c</fullName>
    <label>Points</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Mapper/PlansMapper.cls
global class PlansMapper {
    String name;
    Integer price;
    Integer points;
    List<String> logo;
    String benefits;

    public PlansMapper() {

    }

    public PlansMapper PlansMapperToObject(Plan__c planObject){

        PlansMapper planMapper = new PlansMapper();
        ImageListMapper ImageListMapperInstance = ImageListMapper.getInstance();
        planMapper.name = planObject.Name;
        planMapper.price = (Integer)planObject.Price__c;
        planMapper.points = (Integer)planObject.Points__c;
        planMapper.logo = ImageListMapperInstance.ConvertToImageList(planObject.Logo__c);
        planMapper.benefits = planObject.benefits__c;

        return planMapper;
    }

    public List<PlansMapper> PlansMapperListToObject(List<Plan__c> planObjectList){
        List<PlansMapper> plansMapper = new List<PlansMapper>();
       
        for( Plan__c p : planObjectList ){

            plansMapper.add(PlansMapperToObject(p));
        }

        return plansMapper;

    }
}