force-app/main/default/objects/Catalogue__c/Catalogue__c.object-meta.xml
<CustomObject>
    <label>Catalogue</label>
    <nameField>
        <label>Catalogue Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Catalogues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Publication__c/Publication__c.object-meta.xml
<CustomObject>
    <label>Publication</label>
    <nameField>
        <label>Publication Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Publication__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>130768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Publication__c/fields/Image__c.field-meta.xml
<CustomField>
    <fullName>Image__c</fullName>
    <label>Image</label>
    <length>130768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Publication__c/fields/Tag__c.field-meta.xml
<CustomField>
    <fullName>Tag__c</fullName>
    <label>Tag</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sub_Tags</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Sub_Tags.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Concerts</fullName>
    </customValue>
    <customValue>
        <fullName>Music Festivals</fullName>
    </customValue>
    <customValue>
        <fullName>Fashion Shows</fullName>
    </customValue>
    <customValue>
        <fullName>Opera</fullName>
    </customValue>
    <customValue>
        <fullName>Theatre</fullName>
    </customValue>
    <customValue>
        <fullName>Art &amp; Antique Fairs</fullName>
    </customValue>
    <customValue>
        <fullName>Water Sports</fullName>
    </customValue>
    <customValue>
        <fullName>Sports</fullName>
    </customValue>
    <customValue>
        <fullName>Sightseeing</fullName>
    </customValue>
    <customValue>
        <fullName>Wilderness &amp; Wildlife</fullName>
    </customValue>
    <customValue>
        <fullName>Desert Safari</fullName>
    </customValue>
    <customValue>
        <fullName>Cups &amp; Championships</fullName>
    </customValue>
    <customValue>
        <fullName>Meditation</fullName>
    </customValue>
    <customValue>
        <fullName>Relaxation</fullName>
    </customValue>
    <customValue>
        <fullName>Beauty</fullName>
    </customValue>
    <customValue>
        <fullName>Fitness</fullName>
    </customValue>
    <customValue>
        <fullName>Wellness Festivals</fullName>
    </customValue>
    <customValue>
        <fullName>Spirituality</fullName>
    </customValue>
    <customValue>
        <fullName>Rejuvenation</fullName>
    </customValue>
    <customValue>
        <fullName>Cuisine</fullName>
    </customValue>
    <customValue>
        <fullName>Culture</fullName>
    </customValue>
    <customValue>
        <fullName>History</fullName>
    </customValue>
    <customValue>
        <fullName>Social Happenings</fullName>
    </customValue>
    <customValue>
        <fullName>Seasonal Celebrations</fullName>
    </customValue>
    <customValue>
        <fullName>Family</fullName>
    </customValue>
    <customValue>
        <fullName>Business Travel</fullName>
    </customValue>
    <customValue>
        <fullName>Entrepreneurship</fullName>
    </customValue>
    <customValue>
        <fullName>Trade Shows &amp; Expos</fullName>
    </customValue>
    <customValue>
        <fullName>Incentive Trips &amp; Company Retreats</fullName>
    </customValue>
    <customValue>
        <fullName>Conferences &amp; Events</fullName>
    </customValue>
    <masterLabel>Sub-Tags</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Mapper/PublicationMapper.cls
global class PublicationMapper {
    public String name;
    public Datetime startDate;
    public Datetime endDate;
    public String location;
    public String tags;
    public List<String> images;
    public String description;
    public String id;
    public String catalouge;

    public PublicationMapper() {
       
    }



    public static PublicationMapper getInstance() {
       // if (instance == null) {
        PublicationMapper instance = new PublicationMapper();
       //}
        return instance;
      }
      public  PublicationMapper PublicationObjectToMapper(Publication__c publicationObject){

        PublicationMapper mapper = PublicationMapper.getInstance();
        ImageListMapper ImageListMapperInstance = ImageListMapper.getInstance();
        mapper.name = publicationObject.Name;
        mapper.id = publicationObject.Id;
        mapper.tags = publicationObject.Tag__c;
        mapper.location= publicationObject.Location__c;
        mapper.startDate= publicationObject.Start_Date__c;  
        mapper.endDate= publicationObject.End_Date__c;
        mapper.description= publicationObject.Description__c;
        //mapper.images= publicationObject.Image__c;
        mapper.images= ImageListMapperInstance.ConvertToImageList(publicationObject.Image__c);
        mapper.catalouge = publicationObject.Catalogue__c;

        return mapper;
      }

      public  List<PublicationMapper> PublicationObjectListToMapperList(List<Publication__c> publicationObjectList){

        List<PublicationMapper> mapperList = new List<PublicationMapper>();

        for( Publication__c p : publicationObjectList ){

            mapperList.add(PublicationObjectToMapper(p));
        }

        return mapperList;
      }
}