force-app/main/default/objects/Catalogue__c/Catalogue__c.object-meta.xml
<CustomObject>
    <label>Catalogue</label>
    <nameField>
        <label>Catalogue Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Catalogues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Catalogue__c/fields/Benefits__c.field-meta.xml
<CustomField>
    <fullName>Benefits__c</fullName>
    <label>Benefits</label>
    <length>60768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Catalogue__c/fields/Cancellation_Policy__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Policy__c</fullName>
    <label>Cancellation Policy</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Catalogue__c/fields/Change_Policy__c.field-meta.xml
<CustomField>
    <fullName>Change_Policy__c</fullName>
    <label>Change Policy</label>
    <length>40768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Catalogue__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>City</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Catalogue__c/fields/Emergency_Number__c.field-meta.xml
<CustomField>
    <fullName>Emergency_Number__c</fullName>
    <label>Emergency Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Catalogue__c/fields/House_Rules__c.field-meta.xml
<CustomField>
    <fullName>House_Rules__c</fullName>
    <label>House Rules</label>
    <length>60768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Catalogue__c/fields/Recommendations__c.field-meta.xml
<CustomField>
    <fullName>Recommendations__c</fullName>
    <label>Recommendations</label>
    <length>60768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Catalogue__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hotel</fullName>
            </value>
            <value>
                <fullName>Villa</fullName>
            </value>
            <value>
                <fullName>Store</fullName>
            </value>
            <value>
                <fullName>Musem</fullName>
            </value>
            <value>
                <fullName>Yacht</fullName>
            </value>
            <value>
                <fullName>Car</fullName>
            </value>
            <value>
                <fullName>Beach Club</fullName>
            </value>
            <value>
                <fullName>Night Spot</fullName>
            </value>
            <value>
                <fullName>Fine Dinning</fullName>
            </value>
            <value>
                <fullName>Casual Dinning</fullName>
            </value>
            <value>
                <fullName>Airline</fullName>
            </value>
            <value>
                <fullName>Private Jet</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/City.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Spain</fullName>
    </customValue>
    <customValue>
        <fullName>France</fullName>
    </customValue>
    <masterLabel>City</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Repository/CatalogueRepository.cls
public class CatalogueRepository {
    private static CatalogueRepository instance = null;
    public CatalogueRepository() {

    }

    public static CatalogueRepository getInstance() {
        if (instance == null) {
          instance = new CatalogueRepository();
        }
        return instance;
      }

      public List<Catalogue__c> FindAllCatalogue(){
        return [
          SELECT
          Name,
          Logo__c,
          City__c,
          Address__c,
          Location__c,
          Phone__c,
          Emergency_Number__c,
          Type__c,
          Description__c,
          House_Rules__c,
          Change_Policy__c,
          Cancellation_Policy__c,
          Benefits__c,
          Recommendations__c,
          RecordTypeId	
          FROM Catalogue__c
        ];
      }

      public List<Catalogue__c> FindAllCatalogueByType(String type){
        return [
          SELECT
          Name,
          Logo__c,
          City__c,
          Address__c,
          Location__c,
          Phone__c,
          Emergency_Number__c,
          Type__c,
          Description__c,
          House_Rules__c,
          Change_Policy__c,
          Cancellation_Policy__c,
          Benefits__c,
          Recommendations__c,
          RecordTypeId	
          FROM Catalogue__c
          WHERE Type__c = :type
        ];
      }

      public List<Catalogue__c> FindAllCatalogueByCityGuide(){
        return [
          SELECT
          Name,
          Logo__c,
          City__c,
          Address__c,
          Location__c,
          Phone__c,
          Emergency_Number__c,
          Type__c,
          Description__c,
          House_Rules__c,
          Change_Policy__c,
          Cancellation_Policy__c,
          Benefits__c,
          Recommendations__c,
          RecordTypeId	
          FROM Catalogue__c
          WHERE CityGuide__c = true
        ];
      }
}