force-app/main/default/objects/Catalogue__c/Catalogue__c.object-meta.xml
<CustomObject>
    <label>Catalogue</label>
    <nameField>
        <label>Catalogue Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Catalogues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Catalogue_Photos__c/Catalogue_Photos__c.object-meta.xml
<CustomObject>
    <label>Photos &amp; Links</label>
    <nameField>
        <label>Collection Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Photos  &amp; Links</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Catalogue_Photos__c/fields/Catalogue__c.field-meta.xml
<CustomField>
    <fullName>Catalogue__c</fullName>
    <label>Catalogue</label>
    <referenceTo>Catalogue__c</referenceTo>
    <relationshipLabel>Photos  &amp; Links</relationshipLabel>
    <relationshipName>Photos_Links</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/Repository/CataloguePhotosRepository.cls
public class CataloguePhotosRepository {
    private static CataloguePhotosRepository instance = null;

    private CataloguePhotosRepository() {

    }

    public static CataloguePhotosRepository getInstance() {
        if (instance == null) {
          instance = new CataloguePhotosRepository();
        }
        return instance;
      }

      public List<Catalogue_Photos__c> FindPhotoByCatalogue(String catalogueid){
        return [
          SELECT
          Name,
          Photos_Or_Links__c
          FROM Catalogue_Photos__c
          WHERE Catalogue__c = :catalogueid
        ];}
}