force-app/main/default/objects/Catalogue__c/Catalogue__c.object-meta.xml
<CustomObject>
    <label>Catalogue</label>
    <nameField>
        <label>Catalogue Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Catalogues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Catalogue__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hotel</fullName>
            </value>
            <value>
                <fullName>Villa</fullName>
            </value>
            <value>
                <fullName>Store</fullName>
            </value>
            <value>
                <fullName>Musem</fullName>
            </value>
            <value>
                <fullName>Yacht</fullName>
            </value>
            <value>
                <fullName>Car</fullName>
            </value>
            <value>
                <fullName>Beach Club</fullName>
            </value>
            <value>
                <fullName>Night Spot</fullName>
            </value>
            <value>
                <fullName>Fine Dinning</fullName>
            </value>
            <value>
                <fullName>Casual Dinning</fullName>
            </value>
            <value>
                <fullName>Airline</fullName>
            </value>
            <value>
                <fullName>Private Jet</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Catalogue__c/recordTypes/Accommodation.recordType-meta.xml
<RecordType>
    <fullName>Accommodation</fullName>
    <active>true</active>
    <label>Accommodation</label>
</RecordType>

force-app/main/default/objects/Catalogue__c/recordTypes/Transport.recordType-meta.xml
<RecordType>
    <fullName>Transport</fullName>
    <active>true</active>
    <label>Transport</label>
</RecordType>

force-app/main/default/objects/Company_Info__mdt/Company_Info__mdt.object-meta.xml
<CustomObject>
    <label>Company Info</label>
    <pluralLabel>Company Infos</pluralLabel>
</CustomObject>

force-app/main/default/objects/Company_Info__mdt/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Company_Info__mdt/fields/License_No__c.field-meta.xml
<CustomField>
    <fullName>License_No__c</fullName>
    <label>License No</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Company_Info__mdt/fields/Reg_No__c.field-meta.xml
<CustomField>
    <fullName>Reg_No__c</fullName>
    <label>Reg No</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Company_Info__mdt/fields/Tax_ID__c.field-meta.xml
<CustomField>
    <fullName>Tax_ID__c</fullName>
    <label>Tax ID</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Company_Info__mdt/fields/Url__c.field-meta.xml
<CustomField>
    <fullName>Url__c</fullName>
    <label>Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Opprtunity_Line_Item_Details__c/Opprtunity_Line_Item_Details__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <label>Opprtunity Line Item Details Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opprtunity_Line_Item_Details__c/fields/Adult__c.field-meta.xml
<CustomField>
    <fullName>Adult__c</fullName>
    <label>Adult</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opprtunity_Line_Item_Details__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Number of Bookings</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opprtunity_Line_Item_Details__c/fields/Catalogue__c.field-meta.xml
<CustomField>
    <fullName>Catalogue__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Catalogue</label>
    <referenceTo>Catalogue__c</referenceTo>
    <relationshipLabel>Opportunity Line Items Details</relationshipLabel>
    <relationshipName>Opportunity_Line_Items_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opprtunity_Line_Item_Details__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sub_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>vaccine</fullName>
            </value>
            <value>
                <fullName>PCR</fullName>
            </value>
            <value>
                <fullName>Honeymoon</fullName>
            </value>
            <value>
                <fullName>Group Travel</fullName>
            </value>
            <value>
                <fullName>Wellness</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Cultural and historical</fullName>
            </value>
            <value>
                <fullName>Water sports</fullName>
            </value>
            <value>
                <fullName>Adventure tours</fullName>
            </value>
            <value>
                <fullName>General site seeing tours</fullName>
            </value>
            <value>
                <fullName>cuisine and culture tours</fullName>
            </value>
            <value>
                <fullName>Wilderness and wildLife</fullName>
            </value>
            <value>
                <fullName>Relaxation and Meditation</fullName>
            </value>
            <value>
                <fullName>Sports</fullName>
            </value>
            <value>
                <fullName>Fashion</fullName>
            </value>
            <value>
                <fullName>Product launch</fullName>
            </value>
            <value>
                <fullName>Beauty</fullName>
            </value>
            <value>
                <fullName>Concert</fullName>
            </value>
            <value>
                <fullName>Festival</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>VIP Airport Transfers</fullName>
            </value>
            <value>
                <fullName>VIP Airport Service / Lounge Access</fullName>
            </value>
            <value>
                <fullName>Airport Meet &amp; Greet</fullName>
            </value>
            <value>
                <fullName>Airport Express Check-In</fullName>
            </value>
            <value>
                <fullName>Transfer service</fullName>
            </value>
            <value>
                <fullName>Private Chauffeurs</fullName>
            </value>
            <value>
                <fullName>Hotel</fullName>
            </value>
            <value>
                <fullName>Beach House</fullName>
            </value>
            <value>
                <fullName>Villa</fullName>
            </value>
            <value>
                <fullName>Apartment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opprtunity_Line_Item_Details__c/fields/Child_0_2yr__c.field-meta.xml
<CustomField>
    <fullName>Child_0_2yr__c</fullName>
    <label>Child 0-2yr</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opprtunity_Line_Item_Details__c/fields/Child_3_12yr__c.field-meta.xml
<CustomField>
    <fullName>Child_3_12yr__c</fullName>
    <label>Child 3-12yr</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opprtunity_Line_Item_Details__c/fields/Citizenship__c.field-meta.xml
<CustomField>
    <fullName>Citizenship__c</fullName>
    <label>Citizenship</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Opprtunity_Line_Item_Details__c/fields/Confirmation_Number__c.field-meta.xml
<CustomField>
    <fullName>Confirmation_Number__c</fullName>
    <label>Confirmation Number</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opprtunity_Line_Item_Details__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunity Line Items Details</relationshipLabel>
    <relationshipName>Opportunity_Line_Items_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opprtunity_Line_Item_Details__c/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <label>Contact Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opprtunity_Line_Item_Details__c/fields/Departure_1__c.field-meta.xml
<CustomField>
    <fullName>Departure_1__c</fullName>
    <label>Departure</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Opprtunity_Line_Item_Details__c/fields/Flight_Number__c.field-meta.xml
<CustomField>
    <fullName>Flight_Number__c</fullName>
    <label>Flight Number</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opprtunity_Line_Item_Details__c/fields/Number_of_guests__c.field-meta.xml
<CustomField>
    <fullName>Number_of_guests__c</fullName>
    <label>Number of guests</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opprtunity_Line_Item_Details__c/fields/Operation_Details__c.field-meta.xml
<CustomField>
    <fullName>Operation_Details__c</fullName>
    <label>Operation Details</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opprtunity_Line_Item_Details__c/fields/Prefrence__c.field-meta.xml
<CustomField>
    <fullName>Prefrence__c</fullName>
    <label>preferences</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opprtunity_Line_Item_Details__c/fields/Request_Details__c.field-meta.xml
<CustomField>
    <fullName>Request_Details__c</fullName>
    <label>Request Details</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opprtunity_Line_Item_Details__c/fields/Room__c.field-meta.xml
<CustomField>
    <fullName>Room__c</fullName>
    <label>Room occupancy</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opprtunity_Line_Item_Details__c/fields/Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Sub_Type__c</fullName>
    <label>Sub Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>SubType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opprtunity_Line_Item_Details__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Request_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Request_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Travel Services</fullName>
    </customValue>
    <customValue>
        <fullName>Concierge Services</fullName>
    </customValue>
    <customValue>
        <fullName>Lifestyle Management Services</fullName>
    </customValue>
    <masterLabel>Request Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/VoucherSdocs.cls
/**
 * @description       : 
 * @author            : Mohamed Tarek
 * @group             : 
 * @last modified on  : 01-25-2023
 * @last modified by  : Mohamed Tarek
**/
global class VoucherSdocs implements Callable {

    public Object call(String action, Map<String,Object> args) {
        switch on action {
          
           
            when 'getService'{
                
                return this.getServiceInfo((String) args.get('serviceId'));
            }
            when 'getInfo'{
                return this.getExtraInfo((String) args.get('serviceId'));
            }
            
            when else {
                throw new ExtensionMalformedCallException('Method not implemented');
            }
        }
    }
    public class ExtensionMalformedCallException extends Exception {}
    public Map<String,String> getExtraInfo(String id){
        Map<String,String> result=new Map<String,String>();
        Company_Info__mdt extraInfo=[SELECT Phone__c,Email__c,Address__c,Url__c,Reg_No__c,Tax_Id__c,License_No__c FROM Company_Info__mdt WHERE Label='Egyliere Info'];
        System.debug('ID: '+id);
        Opprtunity_Line_Item_Details__c oppItemDetails=[SELECT Id,Adult__c,Contact__r.Name,Arival_Date__c,Bed_size__c,Hotel__c,Room__c,Type__c,Departure_1__c,Meal_Plan__c,Confirmation_Number__c,Citizenship__c,Sub_Type__c,Number_Of_Guests__c,Catalogue__c,Catalogue__r.Name,Catalogue__r.Phone__c,Catalogue__r.Address__c,Category__c FROM Opprtunity_Line_Item_Details__c WHERE Id=:id];
        result.put('regNo',extraInfo.Reg_No__c);
        result.put('licenseNo',extraInfo.License_No__c); 
        result.put('email',extraInfo.Email__c);
        result.put('phone',extraInfo.Phone__c);
        result.put('address',extraInfo.Address__c);
        result.put('url',extraInfo.Url__c);
        result.put('licenseNo',extraInfo.License_No__c);
        result.put('taxId',extraInfo.Tax_Id__c);
        if(oppItemDetails.Sub_Type__c=='Transport Arrangement - Booking'){
            result.put('title',oppItemDetails.Category__c);
        }else{
        if(oppItemDetails.Catalogue__c!=null){
        result.put('title',oppItemDetails.Catalogue__r.Name);
        }
    }
        return result;
    }
    public SDOC.SDUtil.SDocTable getServiceInfo(String id){
        SDOC.SDUtil.SDocTable table=new SDOC.SDUtil.SDocTable();
        Opprtunity_Line_Item_Details__c[] oppItemDetails=[SELECT  Id,Adult__c,Category__c,Contact__r.Name,Arival_Date__c,Bed_size__c,Hotel__c,Room__c,Type__c,Departure_1__c,Departure__c,Destination__c,Meal_Plan__c,Confirmation_Number__c,Citizenship__c,Sub_Type__c,Number_Of_Guests__c,Departure_Date__c,Prefrence__c,Request_Details__c,Flight_Number__c,Child_0_2yr__c,Child_3_12yr__c,Contact_name__c,Contact_number__c,Booking__c,Transport_Type__c,Operation_Details__c FROM Opprtunity_Line_Item_Details__c WHERE Id=:id];
        if(oppItemDetails.size()!=0){
            Opprtunity_Line_Item_Details__c oppItemDetail=oppItemDetails[0];
            if(oppItemDetail.Sub_Type__c=='Accommodation Management'){
                SDOC.SDUtil.SDocTableRow row=new SDOC.SDUtil.SDocTableRow();
                row.cells.add(new SDOC.SDUtil.SDocTableCell('label','Passenger Name:'));
                row.cells.add(new SDOC.SDUtil.SDocTableCell('value',oppItemDetail.Contact__r.Name));
                table.rows.add(row);
                row=new SDOC.SDUtil.SDocTableRow();
                row.cells.add(new SDOC.SDUtil.SDocTableCell('label','Service Type:'));
                row.cells.add(new SDOC.SDUtil.SDocTableCell('value',oppItemDetail.Sub_Type__c));
                table.rows.add(row);
                row=new SDOC.SDUtil.SDocTableRow();
                row.cells.add(new SDOC.SDUtil.SDocTableCell('label','Check-In:'));
                row.cells.add(new SDOC.SDUtil.SDocTableCell('value',oppItemDetail.Arival_Date__c.format('dd MMMM YYYY')));
                table.rows.add(row);
                row=new SDOC.SDUtil.SDocTableRow();
                row.cells.add(new SDOC.SDUtil.SDocTableCell('label','Check-Out:'));
                row.cells.add(new SDOC.SDUtil.SDocTableCell('value',oppItemDetail.Departure_Date__c.format('dd MMMM YYYY')));
                table.rows.add(row);

                row=new SDOC.SDUtil.SDocTableRow();
                row.cells.add(new SDOC.SDUtil.SDocTableCell('label','Room Occupancy:'));
                row.cells.add(new SDOC.SDUtil.SDocTableCell('value',''+oppItemDetail.Room__c));
                table.rows.add(row);

                row=new SDOC.SDUtil.SDocTableRow();
                row.cells.add(new SDOC.SDUtil.SDocTableCell('label','Bedding:'));
                row.cells.add(new SDOC.SDUtil.SDocTableCell('value',oppItemDetail.Bed_size__c));
                table.rows.add(row);


                row=new SDOC.SDUtil.SDocTableRow();
                row.cells.add(new SDOC.SDUtil.SDocTableCell('label','Room Type:'));
                row.cells.add(new SDOC.SDUtil.SDocTableCell('value',oppItemDetail.Prefrence__c));
                table.rows.add(row);



                row=new SDOC.SDUtil.SDocTableRow();
                row.cells.add(new SDOC.SDUtil.SDocTableCell('label','Meal Plan:'));
                row.cells.add(new SDOC.SDUtil.SDocTableCell('value',oppItemDetail.Meal_Plan__c));
                table.rows.add(row);


                row=new SDOC.SDUtil.SDocTableRow();
                row.cells.add(new SDOC.SDUtil.SDocTableCell('label','Confirmation Number:'));
                row.cells.add(new SDOC.SDUtil.SDocTableCell('value',oppItemDetail.Confirmation_Number__c));
                table.rows.add(row);


            }
            if(oppItemDetail.Sub_Type__c=='Dining & Nightspots Reservations'){
                SDOC.SDUtil.SDocTableRow row=new SDOC.SDUtil.SDocTableRow();
                row.cells.add(new SDOC.SDUtil.SDocTableCell('label','Passenger Name:'));
                row.cells.add(new SDOC.SDUtil.SDocTableCell('value',oppItemDetail.Contact__r.Name));
                table.rows.add(row);
                row=new SDOC.SDUtil.SDocTableRow();
                row.cells.add(new SDOC.SDUtil.SDocTableCell('label','Service Type:'));
                row.cells.add(new SDOC.SDUtil.SDocTableCell('value',oppItemDetail.Sub_Type__c));
                table.rows.add(row);
                row=new SDOC.SDUtil.SDocTableRow();
                row.cells.add(new SDOC.SDUtil.SDocTableCell('label','Date:'));
                row.cells.add(new SDOC.SDUtil.SDocTableCell('value',oppItemDetail.Arival_Date__c.format('dd MMMM YYYY')));
                table.rows.add(row);
                row=new SDOC.SDUtil.SDocTableRow();
                row.cells.add(new SDOC.SDUtil.SDocTableCell('label','Time:'));
                row.cells.add(new SDOC.SDUtil.SDocTableCell('value',oppItemDetail.Arival_Date__c.format('hh:mm a')));
                table.rows.add(row);

                row=new SDOC.SDUtil.SDocTableRow();
                row.cells.add(new SDOC.SDUtil.SDocTableCell('label','Number of guests:'));
                row.cells.add(new SDOC.SDUtil.SDocTableCell('value',''+oppItemDetail.Number_Of_Guests__c));
                table.rows.add(row);


                row=new SDOC.SDUtil.SDocTableRow();
                row.cells.add(new SDOC.SDUtil.SDocTableCell('label','Confirmed By:'));
                row.cells.add(new SDOC.SDUtil.SDocTableCell('value',oppItemDetail.Request_Details__c));
                table.rows.add(row);


                row=new SDOC.SDUtil.SDocTableRow();
                row.cells.add(new SDOC.SDUtil.SDocTableCell('label','Seating:'));
                row.cells.add(new SDOC.SDUtil.SDocTableCell('value',oppItemDetail.Prefrence__c));
                table.rows.add(row);

            }
           
            if(oppItemDetail.Sub_Type__c=='Transport Arrangement - Booking'){
                SDOC.SDUtil.SDocTableRow row=new SDOC.SDUtil.SDocTableRow();
                row.cells.add(new SDOC.SDUtil.SDocTableCell('label','Passenger Name:'));
                row.cells.add(new SDOC.SDUtil.SDocTableCell('value',oppItemDetail.Contact__r.Name));
                table.rows.add(row);
                row=new SDOC.SDUtil.SDocTableRow();
                row.cells.add(new SDOC.SDUtil.SDocTableCell('label','Service Type:'));
                row.cells.add(new SDOC.SDUtil.SDocTableCell('value',oppItemDetail.Sub_Type__c));
                table.rows.add(row);

                row=new SDOC.SDUtil.SDocTableRow(); 
                row.cells.add(new SDOC.SDUtil.SDocTableCell('label','Date & Time:'));
                row.cells.add(new SDOC.SDUtil.SDocTableCell('value',oppItemDetail.Arival_Date__c.format('dd MMMM YYYY - hh:mm a')));
                table.rows.add(row);
                row=new SDOC.SDUtil.SDocTableRow();
                row.cells.add(new SDOC.SDUtil.SDocTableCell('label','Pick-up Address:'));
                row.cells.add(new SDOC.SDUtil.SDocTableCell('value',oppItemDetail.Departure__c));
                table.rows.add(row);

                row=new SDOC.SDUtil.SDocTableRow();
                row.cells.add(new SDOC.SDUtil.SDocTableCell('label','Drop-off Address:'));
                row.cells.add(new SDOC.SDUtil.SDocTableCell('value',oppItemDetail.Destination__c));
                table.rows.add(row);

                row=new SDOC.SDUtil.SDocTableRow();
                row.cells.add(new SDOC.SDUtil.SDocTableCell('label','Number of Travelers:'));
                row.cells.add(new SDOC.SDUtil.SDocTableCell('value',''+oppItemDetail.Booking__c));
                table.rows.add(row);

                row=new SDOC.SDUtil.SDocTableRow();
                row.cells.add(new SDOC.SDUtil.SDocTableCell('label','Transportation Type:'));
                row.cells.add(new SDOC.SDUtil.SDocTableCell('value',oppItemDetail.Transport_Type__c));
                table.rows.add(row);

                row=new SDOC.SDUtil.SDocTableRow();
                row.cells.add(new SDOC.SDUtil.SDocTableCell('label','Vehicle:'));
                row.cells.add(new SDOC.SDUtil.SDocTableCell('value',oppItemDetail.Request_Details__c));
                table.rows.add(row);

                row=new SDOC.SDUtil.SDocTableRow();
                row.cells.add(new SDOC.SDUtil.SDocTableCell('label','Plates Number:'));
                row.cells.add(new SDOC.SDUtil.SDocTableCell('value',oppItemDetail.Operation_Details__c));
                table.rows.add(row);




                row=new SDOC.SDUtil.SDocTableRow();
                row.cells.add(new SDOC.SDUtil.SDocTableCell('label','Driver name:'));
                row.cells.add(new SDOC.SDUtil.SDocTableCell('value',oppItemDetail.Contact_name__c));
                table.rows.add(row);

                row=new SDOC.SDUtil.SDocTableRow();
                row.cells.add(new SDOC.SDUtil.SDocTableCell('label','Driver number:'));
                row.cells.add(new SDOC.SDUtil.SDocTableCell('value',oppItemDetail.Contact_number__c));
                table.rows.add(row);


                row=new SDOC.SDUtil.SDocTableRow();
                row.cells.add(new SDOC.SDUtil.SDocTableCell('label','Confirmation number:'));
                row.cells.add(new SDOC.SDUtil.SDocTableCell('value',oppItemDetail.Confirmation_Number__c));
                table.rows.add(row);





            }


                }
        return table;

    }
}