force-app/main/default/objects/Catalogue__c/Catalogue__c.object-meta.xml
<CustomObject>
    <label>Catalogue</label>
    <nameField>
        <label>Catalogue Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Catalogues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Catalogue__c/fields/Benefits__c.field-meta.xml
<CustomField>
    <fullName>Benefits__c</fullName>
    <label>Benefits</label>
    <length>60768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Catalogue__c/fields/Cancellation_Policy__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Policy__c</fullName>
    <label>Cancellation Policy</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Catalogue__c/fields/Change_Policy__c.field-meta.xml
<CustomField>
    <fullName>Change_Policy__c</fullName>
    <label>Change Policy</label>
    <length>40768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Catalogue__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>City</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Catalogue__c/fields/Emergency_Number__c.field-meta.xml
<CustomField>
    <fullName>Emergency_Number__c</fullName>
    <label>Emergency Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Catalogue__c/fields/House_Rules__c.field-meta.xml
<CustomField>
    <fullName>House_Rules__c</fullName>
    <label>House Rules</label>
    <length>60768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Catalogue__c/fields/Recommendations__c.field-meta.xml
<CustomField>
    <fullName>Recommendations__c</fullName>
    <label>Recommendations</label>
    <length>60768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Catalogue__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hotel</fullName>
            </value>
            <value>
                <fullName>Villa</fullName>
            </value>
            <value>
                <fullName>Store</fullName>
            </value>
            <value>
                <fullName>Musem</fullName>
            </value>
            <value>
                <fullName>Yacht</fullName>
            </value>
            <value>
                <fullName>Car</fullName>
            </value>
            <value>
                <fullName>Beach Club</fullName>
            </value>
            <value>
                <fullName>Night Spot</fullName>
            </value>
            <value>
                <fullName>Fine Dinning</fullName>
            </value>
            <value>
                <fullName>Casual Dinning</fullName>
            </value>
            <value>
                <fullName>Airline</fullName>
            </value>
            <value>
                <fullName>Private Jet</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Catalogue_Photos__c/Catalogue_Photos__c.object-meta.xml
<CustomObject>
    <label>Photos &amp; Links</label>
    <nameField>
        <label>Collection Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Photos  &amp; Links</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Catalogue_Photos__c/fields/Catalogue__c.field-meta.xml
<CustomField>
    <fullName>Catalogue__c</fullName>
    <label>Catalogue</label>
    <referenceTo>Catalogue__c</referenceTo>
    <relationshipLabel>Photos  &amp; Links</relationshipLabel>
    <relationshipName>Photos_Links</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Catalogue_Photos__c/fields/Link__c.field-meta.xml
<CustomField>
    <fullName>Link__c</fullName>
    <label>Link</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Catalogue_Photos__c/fields/Photos__c.field-meta.xml
<CustomField>
    <fullName>Photos__c</fullName>
    <label>Photos</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Catalogue_Photos__c/recordTypes/Link.recordType-meta.xml
<RecordType>
    <fullName>Link</fullName>
    <active>true</active>
    <label>Link</label>
</RecordType>

force-app/main/default/globalValueSets/City.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Spain</fullName>
    </customValue>
    <customValue>
        <fullName>France</fullName>
    </customValue>
    <masterLabel>City</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Mapper/CatalogueMapper.cls
global class CatalogueMapper {

    public String name;
    public List<String> Logo;
    public String city;
    public String address;
    public Map<String,Double> location;
    public String phone;
    public String emergencyNumber;
    public String type;
    public String category;
    public String description;
    public String houseRules;
    public String changePolicy;
    public String cancellationPolicy;
    public String benefits;
    public String recommendations;
    public Map<String,List<String>> photoCatalogues;
    public Map<String,String> linksCatalogues;
   


    public CatalogueMapper() {
    }

    public  CatalogueMapper CatalogueObjectToMapper(Catalogue__c catalogueObject){
        CatalogueMapper catalogueMap = new CatalogueMapper();
        ImageListMapper ImageListMapperInstance = ImageListMapper.getInstance(); 
        RecordTypeRepository recordTypeRepositoryInstance = RecordTypeRepository.getInstance();

        catalogueMap.name = catalogueObject.name;
        catalogueMap.Logo = ImageListMapperInstance.ConvertToImageList(catalogueObject.Logo__c);
        catalogueMap.city = catalogueObject.City__c;
        catalogueMap.address = catalogueObject.Address__c;
        Location loc = catalogueObject.Location__c;
        catalogueMap.location =  new Map<String,Double>();
        If(!(loc == null)){
        catalogueMap.location.put('Latitude', loc.latitude);
        catalogueMap.location.put('Longitude',loc.longitude);}
        catalogueMap.phone = catalogueObject.Phone__c;
        catalogueMap.emergencyNumber = catalogueObject.Emergency_Number__c;
        catalogueMap.type = catalogueObject.Type__c;
        catalogueMap.description = catalogueObject.Description__c;
        catalogueMap.houseRules = catalogueObject.House_Rules__c;
        catalogueMap.changePolicy = catalogueObject.Change_Policy__c;
        catalogueMap.cancellationPolicy = catalogueObject.Cancellation_Policy__c;
        catalogueMap.benefits = catalogueObject.Benefits__c;
        catalogueMap.category  = recordTypeRepositoryInstance.getRecordTypebyId(catalogueObject.RecordTypeId).Name;
        catalogueMap.recommendations = catalogueObject.Recommendations__c;
        catalogueMap.photoCatalogues = photoCataloguesMap(catalogueObject);
        catalogueMap.linksCatalogues = linkCataloguesMap(catalogueObject);

        return catalogueMap;
    }
    
    public Map<String,List<String>> photoCataloguesMap(Catalogue__c catalogueObject){
        CataloguePhotosRepository cataloguePhotosRepositoryInstance = CataloguePhotosRepository.getInstance();
        ImageListMapper ImageListMapperInstance = ImageListMapper.getInstance(); 
        Map<String,List<String>> photoCataloguesMap = new Map<String,List<String>>();
        RecordType rt =[select Id from RecordType where Name = 'Photo Gallery' and SobjectType = 'Catalogue_Photos__c'];
        List<Catalogue_Photos__c> photoCatalogues = cataloguePhotosRepositoryInstance.FindPhotoByCatalogueandRecordType(catalogueObject.Id, rt);

        for(Catalogue_Photos__c c :photoCatalogues ){
            photoCataloguesMap.put(c.Name, ImageListMapperInstance.ConvertToImageList(c.Photos__c));
        }
            return photoCataloguesMap;
    }

    public Map<String,String> linkCataloguesMap(Catalogue__c catalogueObject){
         CataloguePhotosRepository cataloguePhotosRepositoryInstance = CataloguePhotosRepository.getInstance();

        Map<String,String> linkCataloguesMap = new Map<String,String>();
        RecordType rt =[select Id from RecordType where Name = 'Link' and SobjectType = 'Catalogue_Photos__c'];
        List<Catalogue_Photos__c> LinkCatalogues = cataloguePhotosRepositoryInstance.FindPhotoByCatalogueandRecordType(catalogueObject.Id, rt);
        for(Catalogue_Photos__c c :LinkCatalogues ){
            linkCataloguesMap.put(c.Name, c.Link__c);
        }
        return linkCataloguesMap;
    }


    global  List<CatalogueMapper> catalogueObjectListToMapperList(List<Catalogue__c> catalogueObjectList){

        List<CatalogueMapper> mapperList = new List<CatalogueMapper>();

        for( Catalogue__c c : catalogueObjectList ){

            mapperList.add(CatalogueObjectToMapper(c));
        }

        return mapperList;
      }

}